### ISSUE TITLE
Printer only prints one copy when multiple copies are requested, cups is used

### ISSUE THREAD

**Issue by PeterKamm** [OpenPrinting/cups#213] opened 2021-08-01 19:34 UTC
Issue:
Printer only prints one copy when multiple copies are requested, cups is used.

Solution:

In *.ppd:
(for example: sudo nano /etc/cups/ppd/Brother_MFC_L8650CDW.ppd)

Search for:
cupsManualCopies: true

change it to:
cupsManualCopies: True

The *.ppd description is case sensitive. Somebody should fix it in the .ppd-Sources on github!

This permanently fixed this issue on my LM20.2c.
Regards, Peter

**Comment by jsmeix** [comment] 2021-08-03 14:15
This one looks like a duplicate of
https://github.com/OpenPrinting/cups-filters/issues/242
and
https://github.com/OpenPrinting/cups/issues/93

**Comment by michaelrsweet** [comment] 2021-08-03 14:21
@jsmeix Indeed

@PeterKamm Current CUPS and cups-filters should have this covered. In the meantime your workaround is what we would have recommended :)

**Closed by michaelrsweet** 2021-08-03 14:21 UTC
