### ISSUE TITLE
Not able to get ppd list from cups server.

### ISSUE THREAD

**Issue by prashant13patil** [OpenPrinting/cups#63] opened 2020-12-09 10:24 UTC
Distro Name : Ubuntu 20.10
Printers : All

While adding printer through hplip not able to get get ppd list from cups server.
From localhost also not able select hp ppd.
Steps to reproduce:

Open browser
Go to localhost:631 > administration
Add printer > select printer ( not ask for custom ppd direct redirect to successful window)
This issue is inconsistent 5-6 time not working out 10 tries.
The same code is working fine on ubuntu 20.04 which has same cups version as 20.10.

Installed Package:
Cups : 2.3.3
Cups-devel : 2.3.3-3
Cups-image : 2.2.3-3

Error with our code:
Error : No ppd found for model “Model name”

Any update or changes that will fix this issue.

**Comment by michaelrsweet** [comment] 2020-12-09 20:46
@prashant13patil Probably the best way to get Ubuntu support is to file a bug against Ubuntu first. This repository is just the holding ground for the various Linux distributions' CUPS source contributions....

**Comment by tillkamppeter** [comment] 2020-12-09 21:14
Original report: OpenPrinting/cups-filters#317
@prashant13patil, what exactly is your printer model? Which entry did you exactly choose in the list of models and drivers in the CUPS web interface?

**Comment by tillkamppeter** [comment] 2021-01-10 13:56
Perhaps this is the same as issue #65. Please try the correction on `driverless` of cups-filters which is described there.

**Comment by michaelrsweet** [comment] 2021-02-03 16:02
Given the symptoms and Till's last response, closing this as a dupe of issue #65. An intermediate fix has been submitted to cups-filters with longer-term changes being prepared for cups-driverd (in CUPS) and the various desktop print dialogs that depend on drivers instead of letting CUPS manage those things...

**Closed by michaelrsweet** 2021-02-03 16:02 UTC
Labels: duplicate
