### ISSUE TITLE
Print options and  authenticated queues, Mac OS

### ISSUE THREAD

**Issue by chalmerssys** [OpenPrinting/cups#182] opened 2021-04-29 09:20 UTC
I have a CUPS-server with autenticated queues (kerberos) which works for Linux-clients.
But for Mac OS clients user selected options are discarded if the queue is authenticated (the job is printed
but with default options). I reported this here more than a year ago but was told to file a bug report with
Apple Feedback Assistant, which I did. After a while there was the status message "Change required by 3rd party".

Any hope of this being fixed? It would be interesting to know if you have any clue to exactly what goes wrong.

**Comment by michaelrsweet** [comment] 2021-04-29 11:06
@chalmerssys We'll need to see a debug error_log (run `cupsctl --debug-logging` on the server) of a macOS client sending a Kerberos-authenticated print job to understand what is happening. If the problem is indeed on the macOS end I can potentially get Apple to fix things...

That said, Kerberos is nearing its end of support in CUPS. The next CUPS feature release (2.4.0) officially deprecates Kerberos (still works, just a warning that Kerberos is going away in a subsequent release) and will be adding OAuth support as the official replacement. The reasons for this are that a) CUPS has depended on an experimental RFC to support Kerberos with IPP, b) Microsoft is moving away from Kerberos and using OAuth for AD, and c) keeping Kerberos working has been a continual drain on the CUPS developers and packagers.

**Comment by chalmerssys** [comment] 2021-04-29 11:32
OK, here you go..(error_log on the server):

[error_log_auth_opt_fail_mac.txt](https://github.com/OpenPrinting/cups/files/6398184/error_log_auth_opt_fail_mac.txt)

**Comment by michaelrsweet** [comment] 2021-04-29 12:05
@chalmerssys And which options had you specified on the Mac? I see a JPEG file being printed from the Mac, so I assume this was a command-line print job (macOS applications almost always send PDF...)?

**Comment by michaelrsweet** [comment] 2021-04-29 12:05
(maybe a debug error_log from the Mac client would be useful too :)

**Comment by chalmerssys** [comment] 2021-04-29 12:15
The command was:
lp -d test_sv_305 -o ColorModel=RGB Edward-de-Vere-1575.jpg
(same prob. when trying to specify options from Safari)

**Comment by michaelrsweet** [comment] 2021-04-29 12:21
@chalmerssys And the log from the client?

**Comment by chalmerssys** [comment] 2021-04-29 12:23
Here one from  the client, debug2...
error_log_auth_on-mac-client_optfail

**Comment by chalmerssys** [comment] 2021-04-29 12:24
Here's one, debug2....
[error_log_auth_on-mac-client_optfail.txt](https://github.com/OpenPrinting/cups/files/6398467/error_log_auth_on-mac-client_optfail.txt)

**Comment by michaelrsweet** [comment] 2021-04-29 13:29
@chalmerssys Thanks, the Mac client definitely isn't passing the options through in the request, need to investigate why.

What version of macOS is the client using?

**Comment by chalmerssys** [comment] 2021-04-29 13:41
It is running Big Sur 11.3.

**Comment by michaelrsweet** [comment] 2021-05-03 13:00
@chalmerssys OK, so the problem is that the XPC service that macOS uses to run the IPP backend as the user (to get the right Kerberos credentials) isn't passing all of the environment variables the backend uses to determine whether to send the options. I have forwarded my notes to the Apple printing team so we can hopefully have a fix for this.

**Comment by chalmerssys** [comment] 2021-05-03 14:44
Thank you, I'm happy to finally see some progress with this problem!

**Comment by michaelrsweet** [comment] 2021-05-12 21:07
The CUPS fix for this is: 4ae90347a Pass CONTENT_TYPE and FINAL_CONTENT_TYPE to Apple XPC service.

The other half of this will be coming in a future macOS software update.

**Closed by michaelrsweet** 2021-05-12 21:07 UTC
Labels: bug, platform issue, priority-high

**Comment by chalmerssys** [comment] 2021-05-17 08:58
The CUPS fix,  does it have to be applied on the server or only on the client?

**Comment by michaelrsweet** [comment] 2021-05-17 13:07
@chalmerssys Only on the clients, and it will be part of a macOS software update (the CUPS fix is only 1/2 of the full fix...)
