### ISSUE TITLE
Printer instance management not handled as expected

### ISSUE THREAD

**Issue by debiantriage** [OpenPrinting/cups#282] opened 2021-11-07 17:33 UTC
We have a report to Debian from  Martin Zimprich regarding lpoptions ignoring and deleting settings of printer instances:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=998318

I am able to reproduce the main issues described in the report.

-- 
Brian.

**Comment by zdohnal** [comment] 2021-11-08 07:52
Hi Brian,

thank you for reporting the issue!

@debiantriage there is a [fix](https://github.com/OpenPrinting/cups/commit/b53ad5bf3e78e852bac68f82db0d03b479e68026) regarding printer instances in 2.4b1 - and I don't  see it among the [applied patches](https://sources.debian.org/patches/cups/2.3.3op2-3+deb11u1/) for the version you've had problem with.

Would you mind applying the patch and telling me whether it helps with your issue?

**Comment by debiantriage** [comment] 2021-11-09 17:46
Hello Zdenek,

Thanks for the useful pointer.

@zdohnal I fear that applying patches is not amongst my skills. I have asked for help from others to carry out your request. We shall see.

**Comment by zdohnal** [comment] 2021-11-23 06:18
I see in the debian tracker that the patch works, closing as duplicate of #71 .

**Closed by zdohnal** 2021-11-23 06:18 UTC
Labels: duplicate
