### ISSUE TITLE
Printing to CUPS_PDF produces no document

### ISSUE THREAD

**Issue by sundoulos2** [OpenPrinting/cups#424] opened 2022-06-28 00:35 UTC
openSUSE Tumbleweed 20220626
WINE 7.11

The problem started with the v2.4 series of CUPS things. Printing to CUPS-PDF works as expected with every linux application. Printing to CUPS-PDF from any Windows/WINE application fails with no errors displayed. I found the following in cups-pdf-CUPS-PDF_log:

With cups-2.4.2 there is the following:

> Fri Apr 15 21:04:28 2022 [DEBUG] set new gid: lp
> Fri Apr 15 21:04:28 2022 [DEBUG] initialization finished: v3.0.1
> Fri Apr 15 21:04:28 2022 [DEBUG] user identified: username
> Fri Apr 15 21:04:28 2022 [DEBUG] output directory name generated: //home/username/PDF
> Fri Apr 15 21:04:28 2022 [ERROR] failed to create directory: //home/username
> Fri Apr 15 21:04:28 2022 [DEBUG] ERRNO: 30 (Read-only file system)
> Fri Apr 15 21:04:28 2022 [ERROR] failed to create user output directory: //home/username/PDF
> Fri Apr 15 21:04:28 2022 [DEBUG] ERRNO: 30 (Read-only file system)

I reverted cups cups-client cups-config libcups2 libcups2-32bit libcupsimage2 to version 2.3.3 and get the following at the same place in the log:

> Fri Apr 15 21:34:50 2022 [DEBUG] set new gid: lp
> Fri Apr 15 21:34:50 2022 [DEBUG] initialization finished: v3.0.1
> Fri Apr 15 21:34:50 2022 [DEBUG] user identified: username
> Fri Apr 15 21:34:50 2022 [DEBUG] output directory name generated: //home/username/PDF
> Fri Apr 15 21:34:50 2022 [DEBUG] user information prepared
> Fri Apr 15 21:34:50 2022 [DEBUG] spoolfile name created: /var/spool/cups-pdf/SPOOL/cups2pdf-2205
> Fri Apr 15 21:34:50 2022 [DEBUG] source stream ready

With the 6 packages at version 2.3.3, printing works as expected from Windows/WINE applications. In both scenarios, the output directory exists and is writeable by users including lp. I also tried printing from a new WINE prefix and results are the same.

**Comment by jsmeix** [comment] 2022-06-28 07:12
Because of the "Read-only file system" message
I think this is not related to CUPS itself
but a consequence of openSUSE's systemd hardenings, see
https://en.opensuse.org/openSUSE:Security_Features#Systemd_hardening_effort
and https://bugzilla.opensuse.org/show_bug.cgi?id=1181400
which had caused the following issue for openSUSE's CUPS, see
https://bugzilla.opensuse.org/show_bug.cgi?id=1195288
and its duplicates where in particular
https://bugzilla.suse.com/show_bug.cgi?id=1195289
provides the best description of the root cause.

In particular regarding cups-pdf see
https://bugzilla.opensuse.org/show_bug.cgi?id=1195288#c10

The current openSUSE /usr/lib/systemd/system/cups.service
contains
```
[Unit]
Description=CUPS Scheduler
Documentation=man:cupsd(8)
After=network.target nss-user-lookup.target nslcd.service
Requires=cups.socket

[Service]
# added automatically, for details please see
# https://en.opensuse.org/openSUSE:Security_Features#Systemd_hardening_effort
ProtectSystem=full
ProtectHome=true
ProtectHostname=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectControlGroups=true
RestrictRealtime=true
# end of automatic additions
# cupsd needs write access in /etc/cups see
# https://bugzilla.opensuse.org/show_bug.cgi?id=1195288
ReadWritePaths=/etc/cups
# end of SUSE additions
ExecStart=/usr/sbin/cupsd -l
Type=notify
Restart=on-failure

[Install]
Also=cups.socket cups.path
WantedBy=printer.target multi-user.target
```
For details about those systemd hardening settings
see `man systemd.exec`

In general for changes in openSUSE CUPS packages see
https://build.opensuse.org/package/view_file/Printing/cups/cups.changes?expand=1
that contains (excerpts):
```
- Enhanced harden_cups.service.patch by adding
  ReadWritePaths=/etc/cups
  because cupsd needs write access in /etc/cups
  (boo#1195288)
...
- Added hardening to systemd service(s) (bsc#1181400), see
  https://en.opensuse.org/openSUSE:Security_Features#Systemd_hardening_effort
  Added patch: harden_cups.service.patch
```

The current openSUSE harden_cups.service.patch is
https://build.opensuse.org/package/view_file/Printing/cups/harden_cups.service.patch?expand=1

**Comment by zdohnal** [comment] 2022-06-28 12:49
Thank you for letting me know, @jsmeix!

@sundoulos2 are you able to print it if you follow the steps? :

```
$ sudo cp /usr/lib/systemd/system/cups.service /etc/systemd/system/
$ sudo sed -i 's,ProtectHome=true,,' /etc/systemd/system/cups.service
$ sudo systemctl daemon-reload && sudo systemctl restart cups
(try to print to cups-pdf)
```

I can reproduce the issue when I set ```ProtectHome=true``` in cups in Fedora - IMHO cups-pdf can create a systemd drop-in to enable access to home dir when cups-pdf is installed.

I'm closing this as a platform issue, however it would be great if we could get the downstream patches from distros into the project, if it is desirable.

**Closed by zdohnal** 2022-06-28 12:49 UTC

**Comment by jsmeix** [comment] 2022-06-28 13:24
@zdohnal 
it is my plan to create an upstream PR with this openSUSE changes
but I would prefer to wait some more time and see how those changes
actually behave out there in the wild for openSUSE users
to get a better understanding what issues appear in practice.

For example this issue here appeared some longer time
after those changes had been included in April 2022
in openSUSE Tumbleweed which is a rolling release of
up-to-date (stable) software versions.
In contrast those changes will not be included into newest
openSUSE Leap which inherits its basic software
(in particular CUPS) from the latest SLES where
we won't introduce possibly problematic changes.

So one has to wait some longer time to also get
user issue reports for non-standard use cases.

But if you prefer an upstream PR right now
I could do it (perhaps a next week or so).

According to the FAQ at
https://en.opensuse.org/openSUSE:Security_Features#Systemd_hardening_effort
```
Support in older releases
In systemd < 244 some of these options are unknown
and will produce warnings
...
"Unknown key name 'XXX' in section 'Service', ignoring."
```
those changes are not backward compatible with older systemd
so "just adding" them unconditioned to CUPS upstream
will cause issues for users who care about system messages.

**Comment by jsmeix** [comment] 2022-06-28 13:41
What I do not understand is
```
Printing to CUPS-PDF works as expected with every linux application.
Printing to CUPS-PDF from any Windows/WINE application fails ...
```
I do not understand why CUPS-PDF behaves
different from Windows/WINE applications
compared to other Linux applications.

**Comment by sundoulos2** [comment] 2022-06-28 14:29
There's a bit of history to this. There was also an issue with cups-filters, improper cropping and positioning when printing to pdf using landscape mode. Around the same time this thing with printing to CUPS-PDF from WINE failing. 2 months or so ago, there was no issue with printing from linux apps, only from WINE. The latest version of CUPS (2.4.2-1.1) from Factory has a build date of 03 June 2022 and printing is completely broken with that for both linux and WINE applications. Maybe there was another issue altogether that was present then. Whatever it was, removing ProtectHome seems to have fixed it.
