### ISSUE TITLE
Quota reset

### ISSUE THREAD

**Issue by kwilczek** [OpenPrinting/cups#496] opened 2022-10-06 18:28 UTC
Dear All,

I know that there is a quota system (https://openprinting.github.io/cups/doc/accounting.html), but I'm unable to figure out how to reset the quota. Could someone shed some light on this?

We are using 2.3.3 version (Debian 11) and have a really simple use case (I know that this is for all users and that is ok):

- set a limit for `N` pages on the `P` printer for the period of `T` seconds,
- after the `T` period, reset the quota -- set the same limit `N` for the same period `T` again,
- sometimes reset the quota during the `T` period.

Is it possible with the current quota implementation? I tried setting the quota and period to 0, etc. but nothing works. After setting the limit again, I get the info that my quota has already exhausted -- which means that the previous limit is still in use.
And, are there any _alive_ 3rd party quota solutions that you know of? I think that the _pykota_ is EOL and I really can't find anything that is in wider use.

Kind regards,

--
Kamil

**Comment by georgeraraujo** [comment] 2022-10-07 16:57
> And, are there any _alive_ 3rd party quota solutions that you know of? I think that the _pykota_ is EOL and I really can't find anything that is in wider use.

If you're willing to jump through hoops, PyKota [still works](http://lists.pykota.com/pipermail/pykota/2021-August/006870.html).

**Comment by zdohnal** [comment] 2022-10-10 08:32
Dupe of #495

**Closed by zdohnal** 2022-10-10 08:32 UTC
