### ISSUE TITLE
Question: Possibility to customize default attributes for raw IPP queues?

### ISSUE THREAD

**Issue by sesu-bio** [OpenPrinting/cups#395] opened 2022-05-12 14:38 UTC
I want to print pre-rendered files to several IPP printers using raw queues. It works out of the box for some printers. However, others seem to have problems with the attributes CUPS sends by default.

**HP OfficeJet 200 Mobile Printer**: Rejects the jobs because the job-uuid attribute is included.
**Samsung Xpress M2835WD**: Validate-Job works (successful-ok-ignored-or-substituted-attributes) but then the Create-Job fails with client-error-attributes-or-values-not-supported.

I would like to remove the job-uuid and instead include ipp-attribute-fidelity=false. Is it possible? I tried adding the fidelity to the IPP request I send to CUPS but it was not passed to the printer.

**Comment by michaelrsweet** [comment] 2022-05-12 15:34
OK, so "job-uuid" should never be passed by the IPP backend. As for the rest, a debug `error_log` file showing the jobs being printed might be helpful in determining how to fix things in general.

If you just want to submit jobs to the printer directly, use the `ipptool` command, e.g.:

    ipptool -tf FILENAME ipp://HOSTNAME-OR-IP/ipp/print print-job.test

**Comment by sesu-bio** [comment] 2022-05-13 07:53
Thank you for the quick reply!

If possible, I would like to avoid talking to the printer directly as CUPS provides many useful features like job status and support for SOCKET printing. Driverless will be implemented in the future but for now I cannot transition to that.

To rule out incorrect usage by our client software, I reproduced the issue on a Raspberry Pi using the command line tools:
Raspbian GNU/Linux 10 (buster)
CUPS 2.2.10
cups-filters 1.21.6

**HP OfficeJet 200 Mobile Printer**
```
lpadmin -p OfficeJet200 -E -v ipp://<IP>/ipp/print
lp -d OfficeJet200 /tmp/testfile.jpg
```
[OfficeJet200_error_log.txt](https://github.com/OpenPrinting/cups/files/8685036/OfficeJet200_error_log.txt)
[OfficeJet200_pcap.zip](https://github.com/OpenPrinting/cups/files/8685053/OfficeJet200_pcap.zip)

I did a tcpdump to look at the traffic in Wireshark. It looks to me like job-uuid is in fact sent to the printer:
![grafik](https://user-images.githubusercontent.com/73291406/168234774-151b6ed1-06a8-437e-a887-f63fc4b3b2dd.png)


**Samsung Xpress M2835WD**
```
lpadmin -p SamsungXpress -E -v ipp://<IP>/ipp/print
lp -d SamsungXpress /tmp/testfile.jpg
```
[SamsungXpress_error_log.txt](https://github.com/OpenPrinting/cups/files/8685083/SamsungXpress_error_log.txt)
[SamsungXpress_pcap.zip](https://github.com/OpenPrinting/cups/files/8685086/SamsungXpress_pcap.zip)

**Comment by zdohnal** [comment] 2022-05-13 08:43
I can reproduce on 2.4.1 when using raw model.

job-uuid and job-originating-host-name are added here (backend/ipp):

```
2897      /*
2898       * When talking to another CUPS server, send all options...
2899       */
2900 
2901       fputs("DEBUG: Adding all operation/job attributes.\n", stderr);
```

based on the log:

```
 401 D [13/May/2022:07:59:34 +0200] [Job 4] argv[3]="testfile.jpg"
  402 D [13/May/2022:07:59:34 +0200] [Job 4] argv[4]="1"
  403 D [13/May/2022:07:59:34 +0200] [Job 4] argv[5]="finishings=3 number-up=1 job-uuid=urn:uuid:d5a10a16-53b7-3400-57eb-389a62d3898f job-originating-host-name=localhost date-time-at-creation= date-time-at-processing= time-at-                  creation=1652421574 time-at-processing=1652421574 document-name-supplied=testfile.jpg"
  404 D [13/May/2022:07:59:34 +0200] [Job 4] argv[6]="/var/spool/cups/d00004-001"
.
.
.
  549 D [13/May/2022:07:59:34 +0200] [Job 4] job-name=\"testfile.jpg\"
  550 D [13/May/2022:07:59:34 +0200] [Job 4] document-format=\"image/jpeg\"
  551 D [13/May/2022:07:59:34 +0200] [Job 4] Adding all operation/job attributes.
  552 D [13/May/2022:07:59:34 +0200] [Job 4] IPP/2.0 Validate-Job #2
```

It happens because there is no PPD cache because the queue is raw.

**Comment by michaelrsweet** [comment] 2022-05-13 12:04
Well, raw queues have been deprecated for many years now and there isn't an easy way to differentiate between a raw queue and a shared printer queue.

@sesu-bio I guess the question to ask is "why are you doing this, or what are you trying to accomplish?"

**Comment by sesu-bio** [comment] 2022-05-16 06:04
We ship an IoT device with printing capabilities. Many of our customers have very old printers. In addition to that, we need to support some specific printers that are completely incompatible with Linux / Open Source printing. Our solution is to render the documents on a Windows OS that has some generic drivers as well as some printer specific ones installed. The rendered files are then transferred to our Linux device and sent to the printers via CUPS raw queues via SOCKET.
Some of the problems of that solution are limited printer compatibility as well as a lack of a good job status. To address that, we added support for IPP. Driverless is not implemented yet. We hoped that IPP would still work with our existing printing workflow but provide improved printer compatibility and feedback to the user.

**Comment by zdohnal** [comment] 2022-05-26 05:46
> Well, raw queues have been deprecated for many years now and there isn't an easy way to differentiate between a raw queue and a shared printer queue.

@michaelrsweet we couldn't check the URI of the destination, could we? Because shared queue would have ```/printers``` in the uri and the actual printer ```/ipp/print``` ?

**Comment by zdohnal** [comment] 2022-05-26 05:55
> Some of the problems of that solution are limited printer compatibility as well as a lack of a good job status. To address that, we added support for IPP. Driverless is not implemented yet. We hoped that IPP would still work with our existing printing workflow but provide improved printer compatibility and feedback to the user.

If the destinations are capable of supporting some driverless standards, you can use model ```everywhere``` for them, which will create a driver for the printer, but AFAIK still you will be able to print to the printer with preprocessed file in a format which printer accepts (which is the core idea of raw queues).

If the destinations don't use any driverless standard, don't use any standardized PDL (postscript, PCL, raster...) and don't use a driver, you will need to use f.e. ```ncat``` for getting the data to them. If the printers use a such PDL, some of the printer applications (projects are here https://github.com/OpenPrinting/ , and available as SNAPs as well) can help you AFAIK.

**Comment by michaelrsweet** [comment] 2022-05-26 11:31
@zdohnal Checking the URI resource path isn't enough - there are IPP printers that use CUPS and report "/printers/..." instead of "/ipp/print". And that doesn't account for older printers that used different paths before we standardized on a "/ipp/print" prefix for printing.

@sesu-bio You might also look at using [PAPPL](https://www.msweet.org) as the basis of your solution instead of twisting CUPS to do your bidding... :) And in the long term that would get you both driverless support as well as the legacy path you currently use.

**Comment by sesu-bio** [comment] 2022-05-30 09:10
Thank you for your suggestions. We decided against shipping IPP support via raw queues. From our side, no bugfix is needed anymore.

Instead, we plan the following:
1. Ship IPP support via driverless. That should give us good compatibility with most modern printers.
2. For the legacy printers that require Windows drivers, we will implement our own solution for USB and SOCKET printing. This will allow us to upgrade to CUPS 3.0 when it comes out as it remove support for raw queues. Helpful tools we could use include PAPPL and ncat.
3. Optional: to increase compatibility with older printers that don't support driverless and are incompatible with our legacy workflow, we could include printer applications. Unfortunately, we cannot show the user the web interface of the printer application. Ideally, the printer model would be detected automatically but I am not sure if that is planned or even possible.

Does that sound like a sensible plan?

**Comment by zdohnal** [comment] 2022-05-30 12:56
> Instead, we plan the following:
> 
>     1. Ship IPP support via driverless. That should give us good compatibility with most modern printers.

Nice!

> 
>     2. For the legacy printers that require Windows drivers, we will implement our own solution for USB and SOCKET printing. This will allow us to upgrade to CUPS 3.0 when it comes out as it remove support for raw queues. Helpful tools we could use include PAPPL and ncat.

As long as the solution (a printer application of some kind) will support IPP Everywhere standard CUPS 3.0 will be able to see the printers installed in the printer application. PAPPL API provides standard functions to achieving it.

But if the solution doesn't have the IPP Everywhere interface, CUPS 3.0 won't be able to see it.

> 
>     3. Optional: to increase compatibility with older printers that don't support driverless and are incompatible with our legacy workflow, we could include printer applications. Unfortunately, we cannot show the user the web interface of the printer application. Ideally, the printer model would be detected automatically but I am not sure if that is planned or even possible.
> 

Printer application can provide CLI commands for setting up devices, such LPrint does (https://github.com/michaelrsweet/lprint/) . Since PAPPL provides API for autoadding, IMO  you can implement CLI command for auto-adding as well.

> 
> Does that sound like a sensible plan?

LGTM.


Closing this issue because it happens with raw queues, which are deprecated, and we cannot easily make difference between remote CUPS daemon and printer to make adjustments for job attributes.

**Closed by zdohnal** 2022-05-30 12:56 UTC
Labels: bug, priority-low
