### ISSUE TITLE
Adding printer via web frontend: "Connection:"-field gets filled with random unicode garbage.

### ISSUE THREAD

**Issue by dreirund** [OpenPrinting/cups#1007] opened 2024-07-11 17:16 UTC
I use cups version 2.4.10 on [Artix GNU/Linux](http://artixlinux.org/), installed [from Artix' repository](https://packages.artixlinux.org/details/cups).

When I open [the CUPS webinterface administration panel](http://localhost:631/admin), click "*Add Printer*" -> "*Discovered Network Printers: ( ) Brother MFC-L3730CDN series (Brother MFC-L3730CDN series)*" -> "*Continue*" (or also any USB printer I have connected and want to add),  
the "*Connection:*"-field gets pre-filled with garbage, e.g. currently "`�zc`".  
Screenshot:

---

![screenshot-unicode-garbage](https://github.com/OpenPrinting/cups/assets/1590519/8577199d-6514-48f7-b343-cbe1623fee04)

---

The unicode-garbage is different at each invocation. And it also appears when I want to add an USB printer.

Note that in the `/var/log/cups/error_log` the URI seems to be logged correctly:  
```
[...]
D [11/Jul/2024:16:18:13 +0200] [CGI] admin.cgi started...
D [11/Jul/2024:16:18:13 +0200] cupsdSetBusyState: newbusy="Active clients", busy="Active clients"
D [11/Jul/2024:16:18:13 +0200] [Client 8] Server address is "/run/cups/cups.sock".
D [11/Jul/2024:16:18:13 +0200] [Client 8] Accepted from localhost (Domain)
D [11/Jul/2024:16:18:13 +0200] [Client 8] Waiting for request.
D [11/Jul/2024:16:18:13 +0200] [CGI] http=0x5637a9ce5d10
D [11/Jul/2024:16:18:13 +0200] [CGI] cgiSetVariable: SECTION=\"admin\"
D [11/Jul/2024:16:18:13 +0200] [CGI] cgiSetVariable: REFRESH_PAGE=\"\"
D [11/Jul/2024:16:18:13 +0200] [CGI] org.cups.sid cookie is \"e4bf2e4626104fc15c045c706dbabd0b\"
D [11/Jul/2024:16:18:13 +0200] [CGI] cgiSetVariable: org.cups.sid=\"e4bf2e4626104fc15c045c706dbabd0b\"
D [11/Jul/2024:16:18:13 +0200] [CGI] cgiSetVariable: OP=\"add-printer\"
D [11/Jul/2024:16:18:13 +0200] [CGI] cgiSetVariable: DEVICE_URI=\"dnssd://Brother%20MFC-L3730CDN%20series._ipp._tcp.local/?uuid=e3248000-80ce-11db-8000-b42200b6fcb8|Brother MFC-L3730CDN series\"
D [11/Jul/2024:16:18:13 +0200] [CGI] op=\"add-printer\"...
D [11/Jul/2024:16:18:13 +0200] [CGI] do_am_printer: DEVICE_URI=\"dnssd://Brother%20MFC-L3730CDN%20series._ipp._tcp.local/?uuid=e3248000-80ce-11db-8000-b42200b6fcb8|Brother MFC-L3730CDN series\"
D [11/Jul/2024:16:18:13 +0200] [CGI] cgiSetVariable: CURRENT_MAKE=\"Brother\"
D [11/Jul/2024:16:18:13 +0200] [CGI] cgiSetVariable: CURRENT_MAKE_AND_MODEL=\"Brother MFC-L3730CDN series\"
D [11/Jul/2024:16:18:13 +0200] [CGI] cgiSetVariable: PRINTER_INFO=\"Brother MFC-L3730CDN series\"
D [11/Jul/2024:16:18:13 +0200] [CGI] cgiSetVariable: TEMPLATE_NAME=\"Brother_MFC-L3730CDN_series\"
D [11/Jul/2024:16:18:13 +0200] [CGI] cgiSetVariable: DEVICE_URI=\"dnssd://Brother%20MFC-L3730CDN%20series._ipp._tcp.local/?uuid=e3248000-80ce-11db-8000-b42200b6fcb8\"
D [11/Jul/2024:16:18:13 +0200] [CGI] cgiSetVariable: TITLE=\"Add Printer\"
D [11/Jul/2024:16:18:13 +0200] [CGI] cgiSetVariable: SERVER_NAME=\"localhost\"
D [11/Jul/2024:16:18:13 +0200] [CGI] cgiSetVariable: REMOTE_USER=\"root\"
D [11/Jul/2024:16:18:13 +0200] [CGI] cgiSetVariable: CUPS_VERSION=\"CUPS v2.4.10\"
[...]
```

I also attach the logfiles that `cupsd` has created, as well as the `/etc/cups/cupsd.conf` and `/etc/cups/printers.conf`, with sensitive information (hostname, username, printer names) censored (replaced with string `[censored]`):

* [`error_log`](https://github.com/user-attachments/files/16181261/error_log.txt)
* [`access_log`](https://github.com/user-attachments/files/16181262/access_log.txt)
* [`cups-ocr_log`](https://github.com/user-attachments/files/16181263/cups-ocr_log.txt)
* [`cupsd.conf`](https://github.com/user-attachments/files/16181265/cupsd.conf.txt)
* [`printers.conf`](https://github.com/user-attachments/files/16181266/printers.conf.txt)

[&nearr;&hairsp;Here is a discussion about this on the Artix Linux forum](https://forum.artixlinux.org/index.php?topic=7079).

Regards!

**Comment by michaelrsweet** [comment] 2024-07-11 20:06
Dupe of #998.

**Closed by michaelrsweet** 2024-07-11 20:06 UTC
