### ISSUE TITLE
[RFE] Please consider also discovery via unicast DNS-SD

### ISSUE THREAD

**Issue by pemensik** [OpenPrinting/cups#411] opened 2022-06-10 20:57 UTC
On very nice page [dns-sd.org](http://dns-sd.org/) there is link also to [DNS based discovery](http://www.ietf.org/rfc/rfc6763.html). It allows discovery similar to MDNS protocol, but also across routed segments and without requirement for working multicast. I have seen problem with mdns resolution on some wifi networks. I think unicast resolution might be interesting especially for corporates, where only administrator should be allowed to publish printers (or other devices).

Not sue how much does existing Avahi implementation support it or whether it is even a job for it.

**Comment by zdohnal** [comment] 2022-06-13 04:22
@pemensik IMHO this is a dupe of #319 - it would be great if you checked the existing issues before you file a new :) .

**Closed by zdohnal** 2022-06-13 04:22 UTC
