### ISSUE TITLE
2.3.3op2: make test fails on some distributions

### ISSUE THREAD

**Issue by sp1ritCS** [OpenPrinting/cups#155] opened 2021-03-19 12:17 UTC
I'm trying to update the `cups` package for openSUSE to 2.3.3op2.

In addition to changing upstream, I've also decided to run `make check` and `make test` during the build process (rpm `%check` section), 2.3.3op2 manages to compile and check on all targets (SLES 12.5 upto Factory), but the testsuite fails on SLE15.2, Leap 15.1 and Factory zSystems  with `FAIL: 34 error messages, expected 33.`

```
[  417s] Test Summary
[  417s] 
[  417s] PASS: cupsd exited with no errors.
[  417s] PASS: All job control files purged.
[  417s] PASS: Printer 'Test1' correctly produced 37 page(s).
[  417s] PASS: Printer 'Test2' correctly produced 23 page(s).
[  417s] PASS: Printer 'Test3' correctly produced 2 page(s).
[  417s] PASS: 165 requests logged.
[  417s] PASS: CUPS-Get-Default not logged.
[  417s] PASS: 0 emergency messages.
[  417s] PASS: 0 alert messages.
[  417s] PASS: 0 critical messages.
[  417s] FAIL: 34 error messages, expected 33.
[  417s] E [19/Mar/2021:12:04:54.950854 +0000] [Client 2] Returning IPP client-error-bad-request for Get-Jobs (no URI) from localhost.
[  417s] E [19/Mar/2021:12:04:54.953741 +0000] Missing attributes-natural-language attribute.
[  417s] E [19/Mar/2021:12:04:54.953759 +0000] Missing printer-uri, job-uri, or ppd-name attribute.
[  417s] E [19/Mar/2021:12:04:54.953821 +0000] [Client 2] Returning IPP client-error-bad-request for Get-Jobs (no URI) from localhost.
[  417s] E [19/Mar/2021:12:04:54.956154 +0000] Missing attributes-charset attribute.
[  417s] E [19/Mar/2021:12:04:54.956172 +0000] Missing attributes-natural-language attribute.
[  417s] E [19/Mar/2021:12:04:54.956188 +0000] Missing printer-uri, job-uri, or ppd-name attribute.
[  417s] E [19/Mar/2021:12:04:54.956229 +0000] [Client 2] Returning IPP client-error-bad-request for Get-Jobs (no URI) from localhost.
[  417s] E [19/Mar/2021:12:04:54.957767 +0000] Missing attributes-charset attribute.
[  417s] E [19/Mar/2021:12:04:54.957785 +0000] Missing attributes-natural-language attribute.
[  417s] E [19/Mar/2021:12:04:54.957800 +0000] Missing printer-uri, job-uri, or ppd-name attribute.
[  417s] E [19/Mar/2021:12:04:54.957878 +0000] [Client 2] Returning IPP client-error-bad-request for Get-Jobs (no URI) from localhost.
[  417s] E [19/Mar/2021:12:04:54.958804 +0000] Missing printer-uri, job-uri, or ppd-name attribute.
[  417s] E [19/Mar/2021:12:04:54.958853 +0000] [Client 2] Returning IPP client-error-bad-request for Get-Jobs (no URI) from localhost.
[  418s] E [19/Mar/2021:12:04:54.960897 +0000] [Client 2] Returning IPP client-error-bad-request for Get-Jobs (ipp://localhost:8631/jobs) from localhost.
[  418s] E [19/Mar/2021:12:04:54.961922 +0000] [Client 2] Returning IPP server-error-version-not-supported for Get-Jobs (no URI) from localhost.
[  418s] E [19/Mar/2021:12:04:55.203118 +0000] [Client 4] Returning IPP client-error-bad-request for Print-Job (ipp://localhost:8631/printers/Test1) from localhost.
[  418s] E [19/Mar/2021:12:05:02.442505 +0000] [Client 5] Returning IPP client-error-too-many-subscriptions for Create-Printer-Subscriptions (ipp://localhost:8631/printers/Test1) from localhost.
[  418s] E [19/Mar/2021:12:05:02.458837 +0000] [Client 8] Returning IPP client-error-bad-request for Get-Printer-Attributes (no URI) from localhost.
[  418s] E [19/Mar/2021:12:05:02.477194 +0000] [Client 8] Returning IPP client-error-bad-request for Get-Printer-Attributes (no URI) from localhost.
[  418s] E [19/Mar/2021:12:05:02.478330 +0000] Missing attributes-natural-language attribute.
[  418s] E [19/Mar/2021:12:05:02.478388 +0000] [Client 8] Returning IPP client-error-bad-request for Get-Printer-Attributes (ipp://localhost:8631/printers/Test1) from localhost.
[  418s] E [19/Mar/2021:12:05:02.479305 +0000] Missing attributes-charset attribute.
[  418s] E [19/Mar/2021:12:05:02.479350 +0000] Missing attributes-natural-language attribute.
[  418s] E [19/Mar/2021:12:05:02.479401 +0000] [Client 8] Returning IPP client-error-bad-request for Get-Printer-Attributes (ipp://localhost:8631/printers/Test1) from localhost.
[  418s] E [19/Mar/2021:12:05:02.480708 +0000] Missing attributes-charset attribute.
[  418s] E [19/Mar/2021:12:05:02.480728 +0000] Missing attributes-natural-language attribute.
[  418s] E [19/Mar/2021:12:05:02.480785 +0000] [Client 8] Returning IPP client-error-bad-request for Get-Printer-Attributes (ipp://localhost:8631/printers/Test1) from localhost.
[  418s] E [19/Mar/2021:12:05:02.511870 +0000] [Client 8] Returning IPP server-error-version-not-supported for Get-Printer-Attributes (no URI) from localhost.
[  418s] E [19/Mar/2021:12:05:02.514085 +0000] Missing printer-uri, job-uri, or ppd-name attribute.
[  418s] E [19/Mar/2021:12:05:02.514177 +0000] [Client 8] Returning IPP client-error-bad-request for Get-Printer-Attributes (no URI) from localhost.
[  418s] E [19/Mar/2021:12:05:02.590432 +0000] [Client 8] Returning IPP client-error-not-possible for Cancel-Job (ipp://localhost:8631/printers/Test1) from localhost.
[  418s] E [19/Mar/2021:12:05:02.609595 +0000] [Client 8] Returning IPP client-error-not-possible for Cancel-Job (ipp://localhost:8631/printers/Test1) from localhost.
[  418s] E [19/Mar/2021:12:05:02.646590 +0000] [Client 8] Returning IPP client-error-bad-request for Send-Document (ipp://localhost:8631/printers/Test1) from localhost.
[  418s] PASS: 8 warning messages.
[  418s] PASS: 0 notice messages.
[  418s] PASS: 784 info messages.
[  418s] PASS: 23560 debug messages.
[  418s] PASS: 88718 debug2 messages.
[  418s] 
[  418s] Copied log file "access_log-2021-03-19-abuild" to test directory.
[  418s] Copied log file "debug_log-2021-03-19-abuild" to test directory.
[  418s] Copied log file "error_log-2021-03-19-abuild" to test directory.
[  418s] Copied log file "page_log-2021-03-19-abuild" to test directory.
[  418s] Copied report file "cups-str-2021-03-19-abuild.html" to test directory.
[  418s] 
[  418s] 1 tests failed.
[  418s] make: *** [Makefile:241: test] Error 1
[  418s] error: Bad exit status from /var/tmp/rpm-tmp.iN0zmj (%check)
```

The full log is here: [home:sp1rit:branches:Printing/cups](https://build.opensuse.org/package/live_build_log/home:sp1rit:branches:Printing/cups/SLE_15_SP2/x86_64)

**Comment by michaelrsweet** [comment] 2021-03-19 12:28
@sp1ritCS The issue seems to be the Cancel-Job request:

[  418s] E [19/Mar/2021:12:05:02.590432 +0000] [Client 8] Returning IPP client-error-not-possible for Cancel-Job (ipp://localhost:8631/printers/Test1) from localhost.
[  418s] E [19/Mar/2021:12:05:02.609595 +0000] [Client 8] Returning IPP client-error-not-possible for Cancel-Job (ipp://localhost:8631/printers/Test1) from localhost.

I'll have to go through the full log to see the context...

**Comment by michaelrsweet** [comment] 2021-03-19 12:31
@sp1ritCS Actually, it doesn't look like you have the full error_log file available. What I've done for the Github Actions builder is to cat the error_log when the test fails so that I have a full copy of the log present in the build output. If you can add that and provide a link I'll be happy to investigate further.

**Comment by jsmeix** [comment] 2021-03-19 13:12
FYI:
The build environment that is used by the openSUSE Build Service (OBS) is rather limited.
I don't know all the details but in OBS each package is built
within a new from scratch set up virtual machine
that has no access to "something outside".
Furthermore - as far as I know - the built is run as normal user (not as root)
so I think things like running the cupsd within the build environment won't work normally.

**Comment by michaelrsweet** [comment] 2021-03-19 14:46
@jsmeix Spirit is just running the "make test" target as part of building the package, which sets up a cupsd that runs as an ordinary user without any additional software. As Github Actions has similar limitations (WRT accessing build artifacts, etc.) so my setup includes the following when running the automated test suite:

```
make test || cat test/error_log*
```

Basically, if there is an error during the test then I copy the error_log file to the build log. Messy but effective... :)

**Comment by sp1ritCS** [comment] 2021-03-19 15:06
Ok, so this seems to be some kind of race condition that does not have to occur, but apparently occurs more often on s390x (openSUSE:Factory zSystems). 

rpmbuild kills the build process as soon as a procces returns a non-zero exit code, so I had to be a little creative :)
I've replaced make check and make test (it occurs on make check) with
```sh
bash -c 'make %{?_smp_mflags} check; EXIT=$?; if [ $EXIT -gt 0 ]; then cat test/*_log*-$(whoami); fi; exit $EXIT'
bash -c 'make %{?_smp_mflags} test; EXIT=$?; if [ $EXIT -gt 0 ]; then cat test/*_log*-$(whoami); fi; exit $EXIT'
```

As now the log file far exceeds 100 lines, and you need an account on OBS to see the full log, I'll send the full build log, here.
[cups_log_factory_zsystems_s390x.gz](https://github.com/OpenPrinting/cups/files/6172216/cups_log_factory_zsystems_s390x.gz)

**Comment by michaelrsweet** [comment] 2021-03-23 12:55
@sp1ritCS Can you point me to the other patches you are using?

The failure happens for the 7th job in the test. In a working "make test" log, job 7 is just starting its processing when the Cancel-Job request comes in. In your build log the job has already completed. I need to confirm what the expected behavior is...

**Comment by sp1ritCS** [comment] 2021-03-23 16:35
> @sp1ritCS Can you point me to the other patches you are using?

to quote from the specfile, because every patch is documented fairly well:
> // Patch0...Patch9 is for patches from upstream:
> // Source10...Source99 is for sources from SUSE which are intended for upstream:
> // Patch10...Patch99 is for patches from SUSE which are intended for upstream:
> // Patch10 cups-2.1.0-choose-uri-template.patch adds 'smb://...' URIs to templates/choose-uri.tmpl:
> Patch10:       [cups-2.1.0-choose-uri-template.patch](https://build.opensuse.org/package/view_file/home:sp1rit:branches:Printing/cups/cups-2.1.0-choose-uri-template.patch?expand=1)
> // Patch11 cups-2.1.0-default-webcontent-path.patch changes the default path whereto the
> // web content is installed from /usr/share/doc/cups to /usr/share/cups/webcontent
> // because the files of the CUPS web content are no documentation, see CUPS STR #3578
> // and http://bugzilla.novell.com/show_bug.cgi?id=546023#c6 and subsequent comments:
> Patch11:        [cups-2.1.0-default-webcontent-path.patch](https://build.opensuse.org/package/view_file/home:sp1rit:branches:Printing/cups/cups-2.1.0-default-webcontent-path.patch?expand=1)
> // Patch12 cups-2.1.0-cups-systemd-socket.patch Use systemd socket activation properly:
> Patch12:        [cups-2.1.0-cups-systemd-socket.patch](https://build.opensuse.org/package/view_file/home:sp1rit:branches:Printing/cups/cups-2.1.0-cups-systemd-socket.patch?expand=1)
> // Patch100...Patch999 is for private patches from SUSE which are not intended for upstream:
> // Patch100 cups-pam.diff adds conf/pam.suse regarding support for PAM for SUSE:
Patch100:       [cups-pam.diff](https://build.opensuse.org/package/view_file/home:sp1rit:branches:Printing/cups/cups-pam.diff?expand=1)
> // Patch101 cups-2.0.3-additional_policies.patch adds the 'allowallforanybody' policy to cupsd.conf
> // see https://fate.novell.com/303515 and https://bugzilla.suse.com/show_bug.cgi?id=936309
Patch101:       [cups-2.0.3-additional_policies.patch](https://build.opensuse.org/package/view_file/home:sp1rit:branches:Printing/cups/cups-2.0.3-additional_policies.patch?expand=1)
> // Patch103 cups-1.4-do_not_strip_recommended_from_PPDs.patch
> // reverts the change which was added by Michael Sweet in Jan 2007
> // which strips the word "recommended" from NickName in PPDs because
> // at least yast2-printer in SUSE needs it, compare the
> // 'Why not "recommend" PPDs in the NickName?' and the subsequent
> // 'RFC: New Driver Rating/Information Attributes' mail thread on cups@easysw.com:
> Patch103:       [cups-1.4-do_not_strip_recommended_from_PPDs.patch](https://build.opensuse.org/package/view_file/home:sp1rit:branches:Printing/cups/cups-1.4-do_not_strip_recommended_from_PPDs.patch?expand=1)
> // Patch104 cups-config-libs.patch fixes option --libs in cups-config script:
Patch104:       [cups-config-libs.patch](https://build.opensuse.org/package/view_file/home:sp1rit:branches:Printing/cups/cups-config-libs.patch?expand=1)
> // Patch106 Fixes web UI Kerberos authentication (bsc#1175960)
> Patch106:       [fix-negotiate-authentication-between-CGIs-and-scheduler.patch](https://build.opensuse.org/package/view_file/home:sp1rit:branches:Printing/cups/fix-negotiate-authentication-between-CGIs-and-scheduler.patch?expand=1)

(# has been replaced with //, due to markdown on gh)

As you can see, some of these patches appear to be **very** old (up to 15 years) and refer to webpages that don't even exist anymore. Maybe some of them are unneeded nowadays, but I'm unsure.

**Comment by jsmeix** [comment] 2021-03-24 13:13
All our sources to build CUPS for openSUSE are public accessible at
https://build.opensuse.org/package/show/Printing/cups

On "Wed Jan 27 14:43:37 CET 2010" I dropped
"almost all our own patches to enforce a
 reset to almost 100% compliance with upstream", cf.
https://build.opensuse.org/package/view_file/Printing/cups/cups.changes?expand=1

Meanwhile I am no longer the onyl one who maintains CUPS for openSUSE
but as far as I can tell we have no patches at openSUSE that modify some
generic standard behaviour of CUPS - at least we should not have such patches.

I cannot tell about systemd related patches because I don't know about that stuff.
I gave up trying to understand how that stuff works or is meant to work.
I can understand a single simple systemd unit file to start a service but I gave up
with several unit files for several conflicting use cases for one same service.

**Comment by michaelrsweet** [comment] 2021-04-26 20:39
@sp1ritCS Where do we stand with this?

**Comment by sp1ritCS** [comment] 2021-04-27 07:07
> @sp1ritCS Where do we stand with this?

well, for now the testsuite is disabled

---

however, what might be the cause for the unexplainable behaviour are the limited resources (memory) that are provided to the vm. If I have time, I'll try enabling the testsuite and adding a bit of debug output (`free`) before that. If one one the builds fails I could try to replicate that on my local machine by limiting the memory of the vm.

**Comment by michaelrsweet** [comment] 2021-04-27 19:31
@sp1ritCS The test suite does require some amount of memory, storage, networking, and time to run. I haven't been able to duplicate the issue you are seeing, and neither Travis CI (our former CI service) nor Github Actions (current one) show this same problem using the Ubuntu and macOS VMs.

**Comment by michaelrsweet** [comment] 2021-09-17 14:44
@sp1ritCS I'm going to close this as "unable-to-reproduce". If you can reproduce with 2.4.0 (close to beta now) please let me know.

**Closed by michaelrsweet** 2021-09-17 14:44 UTC
Labels: investigating

**Comment by shirelyhhdl** [comment] 2022-07-27 02:34
**Hello, this problem can also occur occasionally in cups-2.4.0 version**
“Returning IPP client-error-not-possible for Cancel-Job ”，this err log appears 2 times

[  220s] FAIL: 34 error messages, expected 33.
[  220s] E [25/Jul/2022:10:31:52.958248 +0000] [Client 2] Returning IPP client-error-bad-request for Get-Jobs (no URI) from localhost.
[  220s] E [25/Jul/2022:10:31:52.958774 +0000] Missing attributes-natural-language attribute.
[  220s] E [25/Jul/2022:10:31:52.958787 +0000] Missing printer-uri, job-uri, or ppd-name attribute.
[  220s] E [25/Jul/2022:10:31:52.958819 +0000] [Client 2] Returning IPP client-error-bad-request for Get-Jobs (no URI) from localhost.
[  220s] E [25/Jul/2022:10:31:52.959219 +0000] Missing attributes-charset attribute.
[  220s] E [25/Jul/2022:10:31:52.959232 +0000] Missing attributes-natural-language attribute.
[  220s] E [25/Jul/2022:10:31:52.959244 +0000] Missing printer-uri, job-uri, or ppd-name attribute.
[  220s] E [25/Jul/2022:10:31:52.959274 +0000] [Client 2] Returning IPP client-error-bad-request for Get-Jobs (no URI) from localhost.
[  220s] E [25/Jul/2022:10:31:52.959681 +0000] Missing attributes-charset attribute.
[  220s] E [25/Jul/2022:10:31:52.959694 +0000] Missing attributes-natural-language attribute.
[  220s] E [25/Jul/2022:10:31:52.959706 +0000] Missing printer-uri, job-uri, or ppd-name attribute.
[  220s] E [25/Jul/2022:10:31:52.959741 +0000] [Client 2] Returning IPP client-error-bad-request for Get-Jobs (no URI) from localhost.
[  220s] E [25/Jul/2022:10:31:52.960130 +0000] Missing printer-uri, job-uri, or ppd-name attribute.
[  220s] E [25/Jul/2022:10:31:52.960165 +0000] [Client 2] Returning IPP client-error-bad-request for Get-Jobs (no URI) from localhost.
[  220s] E [25/Jul/2022:10:31:52.960970 +0000] [Client 2] Returning IPP client-error-bad-request for Get-Jobs (ipp://localhost:8631/jobs) from localhost.
[  220s] E [25/Jul/2022:10:31:52.961348 +0000] [Client 2] Returning IPP server-error-version-not-supported for Get-Jobs (no URI) from localhost.
[  220s] E [25/Jul/2022:10:31:53.018648 +0000] [Client 4] Returning IPP client-error-bad-request for Print-Job (ipp://localhost:8631/printers/Test1) from localhost.
[  220s] E [25/Jul/2022:10:32:00.055408 +0000] [Client 5] Returning IPP client-error-too-many-subscriptions for Create-Printer-Subscriptions (ipp://localhost:8631/printers/Test1) from localhost.
[  220s] E [25/Jul/2022:10:32:00.149059 +0000] [Client 8] Returning IPP client-error-bad-request for Get-Printer-Attributes (no URI) from localhost.
[  220s] E [25/Jul/2022:10:32:00.160887 +0000] [Client 8] Returning IPP client-error-bad-request for Get-Printer-Attributes (no URI) from localhost.
[  220s] E [25/Jul/2022:10:32:00.172884 +0000] Missing attributes-natural-language attribute.
[  220s] E [25/Jul/2022:10:32:00.172928 +0000] [Client 8] Returning IPP client-error-bad-request for Get-Printer-Attributes (ipp://localhost:8631/printers/Test1) from localhost.
[  220s] E [25/Jul/2022:10:32:00.184888 +0000] Missing attributes-charset attribute.
[  220s] E [25/Jul/2022:10:32:00.184903 +0000] Missing attributes-natural-language attribute.
[  220s] E [25/Jul/2022:10:32:00.184941 +0000] [Client 8] Returning IPP client-error-bad-request for Get-Printer-Attributes (ipp://localhost:8631/printers/Test1) from localhost.
[  220s] E [25/Jul/2022:10:32:00.196892 +0000] Missing attributes-charset attribute.
[  220s] E [25/Jul/2022:10:32:00.196908 +0000] Missing attributes-natural-language attribute.
[  220s] E [25/Jul/2022:10:32:00.196951 +0000] [Client 8] Returning IPP client-error-bad-request for Get-Printer-Attributes (ipp://localhost:8631/printers/Test1) from localhost.
[  220s] E [25/Jul/2022:10:32:00.228893 +0000] [Client 8] Returning IPP server-error-version-not-supported for Get-Printer-Attributes (no URI) from localhost.
[  220s] E [25/Jul/2022:10:32:00.241222 +0000] Missing printer-uri, job-uri, or ppd-name attribute.
[  220s] E [25/Jul/2022:10:32:00.241266 +0000] [Client 8] Returning IPP client-error-bad-request for Get-Printer-Attributes (no URI) from localhost.
[  220s] E [25/Jul/2022:10:32:00.351754 +0000] [Client 8] Returning IPP client-error-not-possible for Cancel-Job (ipp://localhost:8631/printers/Test1) from localhost.
[  220s] E [25/Jul/2022:10:32:00.392474 +0000] [Client 8] Returning IPP client-error-not-possible for Cancel-Job (ipp://localhost:8631/printers/Test1) from localhost.
[  220s] E [25/Jul/2022:10:32:00.448922 +0000] [Client 8] Returning IPP client-error-bad-request for Send-Document (ipp://localhost:8631/printers/Test1) from localhost.
[  220s] PASS: 14 warning messages.
[  220s] PASS: 0 notice messages.
[  220s] PASS: 872 info messages.
[  220s] PASS: 24069 debug messages.
[  221s] PASS: 80585 debug2 messages.

**Comment by zdohnal** [comment] 2022-07-27 16:13
@shirelyhhdl @sp1ritCS can you reproduce still on s390x? I've created a PR which will hold the job which we need to cancel, so the additional error shouldn't be generated.

Would you mind testing it?
