### ISSUE TITLE
IPP Everywhere driver not passing correct finishing options to clients

### ISSUE THREAD

**Issue by 74kumi** [OpenPrinting/cups#821] opened 2023-11-09 18:17 UTC
**Describe the bug**
Using cups to allow chromebooks to print. If i use the ppd file on chromebook config i'm missing some options for the printer (not this issue). If i use ipp Everywhere > cups and ipp everywhere > client  which chromebooks do with cups 2.4.7 im missing tray options I can do PPD > cups > ipp everywhere but i get a different set of missing options.

**To Reproduce**
Ive run ipptool -tv ipp://*.*.*.*:631/****** get-printer-attributes.test three different ways and seem to get different results
I have a CUPS 2.4.1 and a CUPS 2.4.6 I seem to get different attributes 
Ipptool to printer IPP> i get hole punch options
Ipptool to cups 2.4.1 PPd printer > no hole punch options
IPPtool to cups 2.4.6 ipp everywhere printer > no hole punch options

**Expected behavior**
I assume ipp get attributes would return the same options all the way to the client ( Printer > Cups > Client)

**Screenshots**

**System Information:**
 - ubuntu 22.04 cups 2.4.1 ubuntu 23.10 cups 24.6
 - Ricoh printer ipp and ppd > cups servers > chromebook clients running cups 2.4.7
 
Il make a feature request if this may be a thing but using cups to filter the number of options being passed to the chromebook ipp everywhere clients would be awesome.

**Comment by ValdikSS** [comment] 2024-01-09 03:24
Upload your ppd file and the results of ipptool.

**Comment by 74kumi** [comment] 2024-02-07 16:21
[Ricoh8300s.ppd.test.txt](https://github.com/OpenPrinting/cups/files/14196476/Ricoh8300s.ppd.test.txt)
[cups.Ricoh8300s.ppd.test.txt](https://github.com/OpenPrinting/cups/files/14196477/cups.Ricoh8300s.ppd.test.txt)
[Copyroom1ipptest.ppd.txt](https://github.com/OpenPrinting/cups/files/14196478/Copyroom1ipptest.ppd.txt)

Since we used ipp everywhere I never specified a ppd file. I grabbed this one from my production cups server that currently dosn't show punching options to end user.

**Comment by michaelrsweet** [comment] 2024-04-05 13:00
OK, so the direct IPP ipptool output shows that the printer supports both punch and staple (top-left, top-right, and edge stitch variants). The CUPS queue shows a staple option but not punch, but punch finishing support has been in there since 2.3.3op2 at least. The PPD file you attached shows comments that wouldn't ordinarily be from the default IPP Everywhere generator...

Can you run the following command - it will produce a machine-readable version of the attributes from your printer which I can use to simulate your printer in my office to test the PPD generator:

    ipptool --ippserver ricoh-pro-8300s.conf ipp://HOST-OR-IP/ipp/print get-printer-attributes.test

Then attach the "ricoh-pro-8300s.conf" file to this issue and I'll continue to investigate.

Thank you!

**Comment by 74kumi** [comment] 2024-04-05 13:45
I had to rename to txt so GitHub would let me attach it.
[ricoh-pro-8300s.txt](https://github.com/OpenPrinting/cups/files/14885620/ricoh-pro-8300s.txt)

**Comment by michaelrsweet** [comment] 2024-04-16 23:52
OK, I've reproduced and assigned to 2.5. Depending on the changes needed, we may be able to backport to 2.4.

**Comment by michaelrsweet** [comment] 2024-04-17 00:11
OK, I've fixed the punch finisher support:

[master 2bc9a48b9] Fix support for simple punch finisher (Issue #821)

For the finishing template support, this particular printer seems to put all of the templates in a single collection value - this is a printer bug and needs to be reported to Ricoh...

**Comment by michaelrsweet** [comment] 2024-04-17 00:26
[2.4.x a994c7318] Fix support for simple punch finisher (Issue #821)

**Comment by michaelrsweet** [comment] 2024-04-17 00:26
Also, I've passed the finishings-col-database issue to my contact at Ricoh...

**Closed as completed by michaelrsweet** 2024-04-17 00:26 UTC
Labels: bug, priority-high
