### ISSUE TITLE
无法添加打印机及无法打印测试页

### ISSUE THREAD

**Issue by madman43** [OpenPrinting/cups#1044] opened 2024-09-05 09:34 UTC
**Before you write the report**
Read the [REPORTING_ISSUES.md](https://github.com/OpenPrinting/cups/blob/master/REPORTING_ISSUES.md) file in the main repository and prepare data mentioned there which looks relevant to you issue.

**Describe the bug**

按照install.md文件编译源码安装后无法测试打印页，提示没有文件，打印机无法添加

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/7c26085d-fe09-49be-a18f-5b0f99aa9f9f)

**System Information:**
 - OS and its version: [e.g. openEuler 22.03 x86_64]
 - Application [e.g. chrome, safari, evince...]
 - CUPS version [e.g. 2.4.11]

**Comment by zdohnal** [comment] 2024-09-06 08:33
Have you installed and set up correctly cups-filters ecosystem (libcupsfilters, libppd, cups-filters) on your system? As our INSTALL.md says:

```
Using CUPS requires additional third-party support software and printer drivers.
These are typically included with your operating system distribution.
```

Additionally, if you downloaded the current master of CUPS repository, it is a not-finished first beta of 2.5, so it is not meant to be shipped at the moment and they might be issues in the code.

If Google translator translated this right, you can't print test page and add printer. Missing cups-filters ecosystem would explain the error "No such file or directory", since test page files are within libcupsfilters.

I don't see the error you get when you add the printer, so I can't say anything about it. But since you installed CUPS from source, I guess your permissions might be incorrect for adding printers, although it is just a wild guess.

Either way, I can't reproduce it on my machine with the latest CUPS release, closing this for now. Do let me know if there is still problem after you look at permission issues and cups-filters installation.

**Closed by zdohnal** 2024-09-06 08:33 UTC
