### ISSUE TITLE
Filter failed (ghostscript) on Ubuntu 24.04

### ISSUE THREAD

**Issue by Stonley890** [OpenPrinting/cups#1071] opened 2024-10-03 22:37 UTC
**Describe the bug**
Attempting to execute a job fails with the following reason: stopped "Filter failed". I'm not entirely sure what's going on, but it seems like something isn't working with ghostscript?

**To Reproduce**
1. [Install and setup CUPS on Ubuntu Server 24.04.](https://ubuntu.com/server/docs/install-and-configure-a-cups-print-server)
2. Add Epson ET-2760 Series printer over USB with PDD file.
3. Print a test page.

**Expected behavior**
The job is completed successfully.

**System Information**
 - OS and its version: Ubuntu 24.04.1 LTS (GNU/Linux 6.8.0-45-generic x86_64)
 - CUPS version: OpenPrinting CUPS 2.4.7
 - Printer: Epson ET-2760 Series

**Screenshot**
<img width="1468" alt="image" src="https://github.com/user-attachments/assets/f06e1031-ebe0-4155-b5d8-c786a9a7c889">

**Additional context**
```
$ sudo ipp-usb check
Configuration files: OK
IPP over USB devices:
 Num  Device              Vndr:Prod  Model
   1. Bus 001 Device 003  04b8:1166  "EPSON ET-2760 Series"
$ lpstat -e
EPSON_ET-2760_Series
EPSON_ET_2760_Series_precision
$ lpstat -t
scheduler is running
system default destination: EPSON_ET-2760_Series
device for EPSON_ET-2760_Series: usb://EPSON/ET-2760%20Series?serial=58364E4A3239383186&interface=1
EPSON_ET-2760_Series accepting requests since Thu 03 Oct 2024 10:02:54 PM UTC
printer EPSON_ET-2760_Series is idle.  enabled since Thu 03 Oct 2024 10:02:54 PM UTC
	cfFilterChain: ghostscript (PID 433150) exited with no errors.
EPSON_ET-2760_Series-5  SM-S928U        815104   Thu 03 Oct 2024 01:08:06 PM UTC
EPSON_ET-2760_Series-6  SM-S928U        815104   Thu 03 Oct 2024 01:09:21 PM UTC
EPSON_ET-2760_Series-7  stonley890        1024   Thu 03 Oct 2024 01:13:14 PM UTC
$ lpinfo -v
network http
serial serial:/dev/ttyS0?baud=115200
network beh
network socket
network lpd
network ipps
network https
network ipp
direct usb://EPSON/ET-2760%20Series?serial=58364E4A3239383186&interface=1
```
[log.txt](https://github.com/user-attachments/files/17250707/log.txt)
[EPSON_ET-2760_Series.ppd.txt](https://github.com/user-attachments/files/17250709/EPSON_ET-2760_Series.ppd.txt)
[USB.txt](https://github.com/user-attachments/files/17250710/USB.txt)

**Comment by Stonley890** [comment] 2024-10-03 22:38
I think this might be the issue?
```
D [03/Oct/2024:22:02:54 +0000] [Job 7] Failed to get profile filename for cups-EPSON_ET-2760_Series
```

**Comment by zdohnal** [comment] 2024-10-04 05:37
Hi @Stonley890 ,

thank you for the report!

I see those lines in the log:

```
D [03/Oct/2024:22:02:54 +0000] [Job 7] EPSON_ET-2760_Series: error while loading shared libraries: libcupsimage.so.2: cannot open shared object file: No such file or directory
D [03/Oct/2024:22:02:54 +0000] [CGI] cgiSetVariable: refresh_page=\"5;URL=https://192.168.0.145:631/printers/EPSON_ET-2760_Series\"
D [03/Oct/2024:22:02:54 +0000] [Job 7] PID 433144 (/opt/epson-inkjet-printer-escpr/cups/lib/filter/epson-escpr-wrapper) stopped with status 127 (File too large)
D [03/Oct/2024:22:02:54 +0000] [CGI] cgiSetVariable: TITLE=\"Jobs\"
```

Since the error about loading libcupsimage.so.2 is in approx. the same time as stopping the filter epson-escpr-wrapper, I suspect the failure of the filter is caused by the error.
I'm not sure how Ubuntu ships libcupsimage.so.2, so I don't know the exact steps what would help you - basically your driver has to load the library to work correctly, and it can't find it at the moment.

Btw your device supports AirPrint - you can turn it on and your device can work without driver.

I'll close the issue for now because the issue is in the driver or in packaging - do let me know if printing still does not work once you fix the driver or if you try AirPrint and it won't work.

=====================
```
D [03/Oct/2024:22:02:54 +0000] [Job 7] Failed to get profile filename for cups-EPSON_ET-2760_Series
```

It is an error related to color profile, it is not critical error which would stop printing.

**Closed by zdohnal** 2024-10-04 05:37 UTC

**Comment by Stonley890** [comment] 2024-10-04 12:46
Thank you so much!
