### ISSUE TITLE
AIX: no pkgconfig so never finds libssl.a, etc.

### ISSUE THREAD

**Issue by aixtools** [OpenPrinting/cups#375] opened 2022-05-01 17:33 UTC
- AIX does not have, by default, `pkgconfig`, so the else block is always going to fire.
- Even if `pkgconfig` is installed - it doesn't have any info on OpenSSL, so that will also fail.

- Having trouble counting and balancing the square brackets [], but something such as this might help:
```
        AC_CHECK_LIB([ssl], [SSL_library_init], [
            AC_MSG_RESULT([yes])
            have_tls="1"
            with_tls="openssl"
            TLSLIBS="-lssl -lcrypto"
            TLSFLAGS=""
            AC_DEFINE([HAVE_TLS], [1], [Do we support TLS?])
            AC_DEFINE([HAVE_OPENSSL], [1], [Do we have the OpenSSL library?])

        ], [
            AC_MSG_ERROR([--with-tls=openssl was specified but neither the OpenSSL nor LibreSSL library were found.])
    ])
```

- Working on a PR, but trying to find the best place to insert `AC_CHECK_LIB`

**Comment by michaelrsweet** [comment] 2022-05-02 11:18
@aixtools Hi, so we don't actually officially support AIX anymore - see the [Supported Platforms](https://github.com/OpenPrinting/cups/wiki/Platforms) wiki page (I need to make sure there is a link from the new CUPS home page for this...) CUPS 2.4 actually removed a bunch of AIX-specific things (particularly for AIX 4's older shared library support) because we had nobody that could/would maintain it...

The problem with simply looking for libssl is that OpenSSL also needs libcrypto - pkg-config takes care of that detail but adding a legacy autoconf check will require checking for *both* libraries (with libcrypto first) to ensure that the check will work (a static libssl won't automatically include libcrypto). That's not a huge problem but it makes the autoconf check code a little more complicated.

WRT a PR, we'll consider it. You'll want to put it in the "openssl" check as an else clause after the PKGCONFIG check, e.g.:

```
AS_IF([test $with_tls = yes -o $with_tls = openssl], [
    AS_IF([test "x$PKGCONFIG" != x], [
        AC_MSG_CHECKING([for openssl package])
        AS_IF([$PKGCONFIG --exists openssl], [
            AC_MSG_RESULT([yes])
            have_tls="1"
            with_tls="openssl"
            TLSLIBS="$($PKGCONFIG --libs openssl)"
            TLSFLAGS="$($PKGCONFIG --cflags openssl)"
            PKGCONFIG_REQUIRES="$PKGCONFIG_REQUIRES openssl"
            AC_DEFINE([HAVE_TLS], [1], [Do we support TLS?])
            AC_DEFINE([HAVE_OPENSSL], [1], [Do we have the OpenSSL library?])
        ], [
            AC_MSG_RESULT([no])
        ])
>   ], [
>     YOUR NEW TESTS GO HERE
    ])
```

**Comment by aixtools** [comment] 2022-05-03 14:44
Thanks for the pointer. I was having a hard time deciding where it should go.

And thanks for the hint to look for libcrypto first.

What do you actually mean by AIX v4 shared library support? The normal AIX shared library is an archive that can hold both shared and static libraries - in both 32-bit and 64-bit format (ABI).

Not sure how AIX v4 is any different from what is common now (or do you mean v4 is when the current format first appeared).

**Comment by aixtools** [comment] 2022-05-03 14:46
As to supporting AIX - CUPS is a pre-requisite for building OpenJDK. I think I mentioned that in the 'discussion'. Don't know why, but it is why I am going through this now. FYI.

**Comment by michaelrsweet** [comment] 2022-05-03 14:55
@aixtools What I mean is that the CUPS build system used to provide shared library support by creating `libcups_s.a` archives (which was the only way shared libraries worked for AIX 4.x), but more "standard" shared objects (`libcups.so.2`) for AIX 5.x. But all of that build support code was dumped in CUPS 2.4.

**Comment by aixtools** [comment] 2022-05-03 15:04
Curious: why not use  https://www.gnu.org/software/autoconf-archive/ax_check_openssl.html

**Comment by michaelrsweet** [comment] 2022-05-03 15:38
@aixtools Because I've found that archive to be hit-or-miss and *most* platforms provide pkg-config these days which greatly simplifies things. If I *did* use something from there I'd be copying it (the whole file) into the repository and including it, as no system has these macros installed as standard. Also, there is always the license problem - at least this macro appears to be using a BSD-style ("all permissive") license, but not all of them are so generous...

**Comment by aixtools** [comment] 2022-05-04 08:37
I understand that you would use the whole thing (fyi, I found it via Python which uses the full text - m4 is not my thing).

Q. Adoptium has something activated so that a PR can be put in 'Draft' status. That is probably best for the PR I opened on this, as they are just examples - to see if I could get it working.

FYI: These are files with modifications (some hand made). (Re-running make DESTDIR=xxx install, for verification) - to give an impression of what I found and/or hacked-in to get it to build.
```
aixtools@x064:[cups-2.4.1.1]git diff master | grep +++
+++ b/.gitignore
+++ b/backend/snmp.c
+++ b/config-scripts/cups-tls.m4
+++ b/configure
+++ b/configure.ac
+++ b/cups/Makefile
+++ b/cups/http.c
+++ b/tools/Makefile
+++ b/tools/ippeveprinter.c
```

**Comment by aixtools** [comment] 2022-05-04 09:30
I built autoconf-2.71 - and this is the short list:
```
+++ b/.gitignore
+++ b/backend/snmp.c
+++ b/config-scripts/cups-tls.m4
+++ b/configure
+++ b/cups/Makefile
+++ b/cups/http.c
+++ b/tools/Makefile
+++ b/tools/ippeveprinter.c
```
- .gitignore is only relevant because I am building in-tree, normally I build out of tree and do not need additions to .gitignore
- The three `.c` files are minor things, imho, likely caused by differences in how gcc and xlc look at source code.
I am not saying these changes are the best way to fix it, but for a prototype build - they work.
- `configure` is the expected change - after the change to `config-scripts/cups-tls.m4`. As you mention above, better is to include the complete macro, rather than an extract.
- `cups/Makefile` and `tools/Makefile` - are just a text change so I could experiment (so, disregard).
- what does not show up - and I did not have a the time to figure out how to make these changes in `configure.ac` are the changes to Makedefs **after** ./configure has finished.
a) the `.m4` file still needs to update TLSLIBS (my error)
b) DSOFLAGS - these are the most basic AIX loader flags (i.e., more complex options are possible).
c) LDFLAGS: when we get into the tools area - as the default for AIX is to not add missing shared libraries to a new shared library - the library flags need to be provided when the applications are being built. This was the final bit of magic that got everything working.

- the end result, however, lacks /usr/lib/libcups.a (or /opt/aixtools/lib/libcups.a) - only the shared (.so) files are there. The file libcups.a is created however.
```
root@x065:[/data/prj/aixtools/cups/cups-2.4.1.1/X32/opt/aixtools/lib]ls -l
total 80
drwxr-xr-x  10 bin      bin            4096 May 04 08:46 cups
lrwxrwxrwx   1 root     system           12 May 04 2022  libcups.so -> libcups.so.2
-rwxr-xr-x   1 bin      bin            4681 May 04 08:46 libcups.so.2
lrwxrwxrwx   1 root     system           17 May 04 2022  libcupsimage.so -> libcupsimage.so.2
-rwxr-xr-x   1 bin      bin            4694 May 04 08:46 libcupsimage.so.2
drwxr-xr-x  14 bin      bin            4096 May 04 08:46 locale
drwxr-xr-x   2 bin      bin            4096 May 04 08:46 pkgconfig
```
FYI:
```
root@x065:[/data/prj/aixtools/cups/cups-2.4.1.1]find . -name \*.a
./backend/libbackend.a
./cgi-bin/libcupscgi.a
./cups/libcupsimage.a
./cups/libcups.a
./ppdc/libcupsppdc.a
./scheduler/libcupsmime.a
```

**Comment by michaelrsweet** [comment] 2022-05-04 12:28
Try this:

[master dd9310639] Look for OpenSSL the old way if pkg-config is not available (Issue #375)

**Comment by aixtools** [comment] 2022-05-17 11:32
I'll rebuild next week. My apologies for the delay.

**Comment by aixtools** [comment] 2022-07-15 12:09
:blush: working on it now.

**Comment by aixtools** [comment] 2022-07-15 12:36
Starting from ` git worktree add ../cups-2.4.2 v2.4.2`
a) run `CC=xlc_r OBJECT_MODE=64 configure --prefix=/opt/aixtools`
b) in tools need to manually add: `-lssl -lcrypto` SO:

With this:
```
aixtools@x064:[cups-2.4.2]diff -u Makedefs Makedefs.patched
--- Makedefs    2022-07-15 12:33:56.000000000 +0000
+++ Makedefs.patched    2022-07-15 12:31:05.000000000 +0000
@@ -155,7 +155,7 @@
                        $(TLSFLAGS) -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT \
                        $(ONDEMANDFLAGS) $(OPTIONS)
  ALL_DSOFLAGS  =       -L../cups   $(DSOFLAGS) $(OPTIM)
- ALL_LDFLAGS   =       -L../cups   $(LDFLAGS)  \
+ ALL_LDFLAGS   =       -L../cups   $(LDFLAGS)  $(TLSLIBS) \
                         $(OPTIM)
  ARCHFLAGS     =
  ARFLAGS               =       crvs
```
it all works as expected.

**Comment by michaelrsweet** [comment] 2022-07-17 22:48
@aixtools OK, so `ALL_LDFLAGS` most definitely should not contain `TLSLIBS`. `LINKCUPS` and `LINKCUPSSTATIC` are where this needs to happen.

I suspect the issue is that AIX shared libraries work more like dynamically loaded static libraries, so we need to change the definition of LINKCUPS on AIX...

**Comment by michaelrsweet** [comment] 2022-07-17 22:53
Try this:

[master cac6d48ad] Fix link libraries on AIX (Issue #375)

**Comment by aixtools** [comment] 2022-08-01 07:57
First test on my OSS management system (not what I normally use to build, AIX 7.1):
```
configure: error: --with-tls=yes was specified but no compatible TLS libraries could be found.

Installed:
openssl.base:openssl.base:1.1.1.1200 (so that would be 1.1.1l (letter l) iirc.
```
- The OpenSSL version installed is the same one I used two weeks ago (just checked).
- The configure script runs fine on the normal build system (AIX 5.3)
- The `make` on AIX 5.3 fails at:
```
Compiling snmp.c...
Linking libcups.so.2...
Linking libcupsimage.so.2...
xlc_r: 1501-228 (W) input file IBS not found
make[1]: *** [Makefile:425: libcupsimage.so.2] Error 252
make: *** [Makefile:43: all] Error 1
root@x065:[/data/prj/aixtools/cups/cups-2.4.3]
```
Note: at the specific commit you requested:
```
commit cac6d48addd4be360ef558fbd0cdc3ccfe72505d (HEAD)
Author: Michael R Sweet <michael.r.sweet@gmail.com>
Date:   Sun Jul 17 18:52:35 2022 -0400

    Fix link libraries on AIX (Issue #375)

```

**Comment by michaelrsweet** [comment] 2022-08-02 15:38
@aixtools Are you able to provide the config.log or Makedefs files as well?

**Comment by aixtools** [comment] 2022-08-03 07:06
- START:
```
aixtools@x064:[cups-master]git worktree add ../cups-2.4.3 cac6d48addd4be360ef558fbd0cdc3ccfe72505d
Preparing worktree (detached HEAD cac6d48ad)
Updating files: 100% (1312/1312), done.
HEAD is now at cac6d48ad Fix link libraries on AIX (Issue #375)
aixtools@x064:[cups-master]cd ../*3
aixtools@x064:[cups-2.4.3]
```
- With pkg-config, but no support of OpenSSL:
```
aixtools@x064:[cups-2.4.3]/opt/bin/pkg-config --list-all
libpcre      libpcre - PCRE - Perl compatible regular expressions C library with 8 bit character support
libpcrecpp   libpcrecpp - PCRECPP - C++ wrapper for PCRE
expat        expat - expat XML parser
libpcreposix libpcreposix - PCREPosix - Posix compatible interface to libpcre
python3      Python - Python library
python-3.6m  Python - Python library
libcurl      libcurl - Library to transfer files with ftp, http, etc.
python-3.6   Python - Python library
sqlite3      SQLite - SQL database engine
liblzma      liblzma - General purpose data compression library
```
**Note:** The packages above are ones I have built. No such information exists for any IBM (AIX) software (_package_.pc files).
```
aixtools@x064:[cups-2.4.3]CC=xlc_r OBJECT_MODE=64 ./configure --prefix=/opt/aixtools
```
- Results: on this system (x064) - no `Makedefs` created. `config.log` attached as `config.x064.log`

[config.x064.log](https://github.com/OpenPrinting/cups/files/9248812/config.x064.log)

- Repeat `configure` on system without `pkg-config`
```
root@x065:[/data/prj/aixtools/cups/cups-2.4.3]CC=xlc_r OBJECT_MODE=64 ./configure --prefix=/opt/aixtools
```
- Attaching as `Makedefs.x065.txt` and `config.x065.log`

[config.x065.log](https://github.com/OpenPrinting/cups/files/9248835/config.x065.log)
[Makedefs.x065.txt](https://github.com/OpenPrinting/cups/files/9248836/Makedefs.x065.txt)

**Comment by michaelrsweet** [comment] 2022-09-22 16:42
@aixtools Sorry this took so long, try the lasted from master:

[master 634c8cc2f] Potentially fix the last AIX configure bug (Issue #375)

**Comment by AtariDreams** [comment] 2022-11-17 15:41
So are we ready to close this or?

**Comment by zdohnal** [comment] 2023-09-13 11:07
No response for a year, closing.

**Closed by zdohnal** 2023-09-13 11:07 UTC
Labels: enhancement, priority-low, platform issue, waiting for reporter

**Comment by listocheklss** [comment] 2025-05-30 12:15
Is it possible that the installation path is simply incorrect?
how should I?
cups cups-filters lib cups libcups filters
