### ISSUE TITLE
mDNS hostname in device URI is not resolved before connecting to the printer during permanent IPP Everywhere queue installation

### ISSUE THREAD

**Issue by Zeioth** [OpenPrinting/cups#340] opened 2022-02-23 00:41 UTC
To generate the ppd of my printer, I went to http://localhost:631/admin added my printer, and choose the model. Works. all good.

This has generated '/etc/cups/ppd/EPSON_ET-1810_Series.ppd' so I tought "Cool, I'm gonna create the printer through a command, so I don't have to manually configure it every time I reinstall my system".

So I ran

    lpadmin -p epson-et1810 -E -v ipps://EPSON%20ET-1810%20Series._ipps._tcp.local/ -m /etc/cups/ppd/EPSON_ET-1810_Series.ppd

And it doesn't work. Doesn't add the printer. The output is:

    lpadmin: Printer drivers are deprecated and will stop working in a future version of CUPS.
    lpadmin: cups-driverd failed to get PPD file - see error_log for details.
    lpadmin: The printer or class does not exist.

Where is any way to bypass this error?
Thank you.

**Comment by zdohnal** [comment] 2022-02-23 06:09
Hi @Zeioth ,

thank you for the question and here are answers and tips:

1. if you install print queue via lpadmin with a file, -P is the option you seek,
2. since the device uri shows ipps and mDNS hostname, my take is your printer can do AirPrint, so it is supported in CUPS by IPP Everywhere - so you can install a permanent queue for your printer by ```-m everywhere```
3. if your machine (laptop, desktop PC) lives in trusted network, you don't need to install the queue at all - applications which support CUPS temporary queues are able to pick up the queue when you are going to print and the queue disappears after successful printing. If an application doesn't support this, it would be great if you reported the fact to them and ask them to support CUPS temporary queues.

I hope it helps and have a nice day :)

**Comment by Zeioth** [comment] 2022-02-23 06:24
Good morning.

1. According to man, the argument -P is deprecated, -p seems to be the right one.
2. If I do that, the printer only prints garbage, instead of the content of the file to print. Meaning, the drivers would not be correct.
3. Answering you, I normally print all files in a certain directory with this alias:

```
print_pdfs_in_current_dir() {
  # Prints all the files in the specified document 
  PRINT_FORMAT="A4"
  PRINT_QUALITY="4"

  TOTAL_FILES=$(ls -l $STAGED_DIR | grep pdf | wc -l)
  current_file=0

  echo "FILES ADDED TO PRINTING QUEUE..."
  echo "run print-list to see the current status."
  echo "================================"
  for filename in $PWD/*.pdf; do
    [ -e "$filename" ] || continue

    # Rest of the loop here
    echo "Printing file $current_file/$TOTAL_FILES... → $filename"
    lp -t "$filename" -n 1 -o print-quality="$PRINT_QUALITY" -o media="$PRINT_FORMAT" "$filename"
  done
  echo "================================"
  echo "PRINTING JOBS STARTING"
}
```

I don't see a good reason to close the issue. If you could re-open it that would be great.

**Comment by zdohnal** [comment] 2022-02-23 07:21
> Good morning.
> 
>     1. According to man, the argument -P is deprecated, -p seems to be the right one.
> 

1. You're mixing two things together - -p sets the name for your print queue, -P sets a file you pass as an argument as print queue driver, f.e.:

```
$ lpadmin -p test -v socket://192.168.5.5 -P /path/to/the/file -E
```

2. If you care about deprecation, then from the man page:

```
       -m model
            Sets a standard PPD file for the printer from the model directory or using one of the driver interfaces.  Use the -m option with the lpinfo(8)
            command to get a list of supported models.  The model "raw" clears any existing PPD file and the model "everywhere" queries  the  printer  re‐
            ferred  to by the specified IPP device-uri.  Note: Models other than "everywhere" are deprecated and will not be supported in a future version
            of CUPS.
```

>     2. If I do that, the printer only prints garbage, instead of the content of the file to print. Meaning, the drivers would not be correct.

Once you use the correct model (-m everywhere) or (if you insist) a file with correct option, the permanent queue should work. But you don't need to install the queue at all, because it looks like it is supported by IPP Everywhere -> you can use temp queue.

> 
>     3. Answering you, I normally print all files in a certain directory with this alias:
> 
> 
> ```
> print_pdfs_in_current_dir() {
>   # Prints all the files in the specified document 
>   PRINT_FORMAT="A4"
>   PRINT_QUALITY="4"
> 
>   TOTAL_FILES=$(ls -l $STAGED_DIR | grep pdf | wc -l)
>   current_file=0
> 
>   echo "FILES ADDED TO PRINTING QUEUE..."
>   echo "run print-list to see the current status."
>   echo "================================"
>   for filename in $PWD/*.pdf; do
>     [ -e "$filename" ] || continue
>     echo "Printing file $current_file/$TOTAL_FILES... → $filename"
>     lp -t "$filename" -n 1 -o print-quality="$PRINT_QUALITY" -o media="$PRINT_FORMAT" "$filename"
>   done
>   echo "================================"
>   echo "PRINTING JOBS STARTING"
> }
> alias print-start="print_pdfs_in_current_dir"
> alias print-cancel="cancel -a"
> alias print-list="lpq"
> ```
> 

The temp queue works with your setup as well - just check whether CUPS actually sees it - which means the printer isn't on the list of accepting printers (output of ```lpstat -a```), but it is on the list of existing printers (```lpstat -e```).

**Comment by michaelrsweet** [comment] 2022-02-23 14:40
@Zeioth The PPD file in /etc/cups/ppd isn't where you'll find it on a fresh system, it is the currently configured PPD for that queue. Ordinarily PPD files are copied either from a driver information file (/usr/share/cups/drv), a PPD file (/usr/share/cups/ppd), a driver interface program (used by Gutenprint in particular - /usr/lib/cups/driver), or from a PPD generated by CUPS for an IPP printer.

For non-IPP printers, the `lpinfo -m` command can be used to find the driver name you can pass to lpadmin with the `-m` option. For IPP printers you just pass `-m everywhere` to lpadmin to generate a PPD for the printer.

The `-P` and `-i` options specify a path to a PPD file. You only use these options for a PPD file in a non-standard location.

But as @zdohnal mentioned, for any printer sold in the last 10 years or so you probably want to use the "everywhere" model or just use (automatically-created) temporary queues.

**Comment by Zeioth** [comment] 2022-02-23 16:24
Hello thank you for your answers:

-m everywhere is incompatible with my new adquired printer (see photo)
![20220223_171437](https://user-images.githubusercontent.com/3357792/155360997-ecc3f08b-d101-45ca-915f-eac0f10e70c7.jpg)

About -m -i and -P I get a deprecation error that prevents lpadmin to add the printer.

So effectively I had no way to add my printor using the command line

**Comment by michaelrsweet** [comment] 2022-02-23 16:40
@Zeioth The deprecation warning does not prevent the queue from being added. Not having the PPD file in the location you specify *will*.

(deprecation == warning, obsolete == error)

**Comment by michaelrsweet** [comment] 2022-02-23 16:45
@Zeioth And looking at the EPSON ET-1810, I'm astonished that it doesn't support AirPrint but you need to make a copy of the PPD file (or use the `lpinfo -m` command to find the model name) to run a fresh lpadmin command - as I said before the PPD file in /etc/cups/ppd is only present for an existing print queue, it is not where the files are copied from!

**Comment by Zeioth** [comment] 2022-02-23 17:10
Thank you @michaelrsweet .

lpinfo -m doesn't list my printer (which is strange because I can see it listed in http://localhost:631/admin).
![screenshot_2022-02-23_18-07-04_288174983](https://user-images.githubusercontent.com/3357792/155370102-836699bf-b066-415d-a866-9f472a9e7454.png)

I also checked the directory /usr/share/foomatic/db/source/PPD/Epson and there is not PPD for my model.

**Comment by Zeioth** [comment] 2022-02-23 17:20
Ok so, I went to epson's website and [I found the PPD for my printer](http://download.ebz.epson.net/dsc/search/01/search/searchModule). Unexpectedly, epsom seem to have pretty good linux support.

    lpadmin -p epson-et1810 -E -v ipps://EPSON%20ET-1810%20Series._ipps._tcp.local/ -i /home/zeioth/tweaks/misc/printers/Epson-ET-1810_Series-epson-escpr-en.ppd # Add the printer to lp
    lpadmin -d epson-et1810 # set as default printer

This time the command added the printer correctly (currently testing to print something).

**Comment by Zeioth** [comment] 2022-02-23 18:29
@michaelrsweet I just noticed the printer prints correctly through the protocol dnssd (added from cups web server).

What would be the format to add a dnssd printer by using lpadmin?

**Comment by michaelrsweet** [comment] 2022-02-23 18:32
@Zeioth The "dnssd" backend just resolves the correct protocol from those the printer reports, so if you do `lpstat -v` on a configured printer you will see what the device URI is to pass with the `-v` option to lpadmin.

Similarly, you can use `lpinfo -v` to list the available printers and their device URIs.

**Comment by Zeioth** [comment] 2022-02-23 18:37
Oh that's a shame

    lpadmin -p epson-et1810 -E -v dnssd://EPSON%20ET-1810%20Series._ipp._tcp.local -m everywhere

Adds the printer correctly but still prints garbage when used with -m everywhere. It seems the printer it just not compatible with the IPP everywhere, actually.

**Comment by zdohnal** [comment] 2022-02-24 06:23
@Zeioth 

I'm sorry, I've misunderstood you - I thought you didn't use ```-m everywhere``` or '-P 'file'' and that's when you got the error. If I understood you have problems with ```-m everywhere``` or otherwise passed a correct options, I wouldn't close the issue.

@Zeioth Would you mind providing the information from the following steps:
==========================================================

1. It would be great if you could attach the file ```output.txt``` of the following command here as a file (it needs .txt suffix):

```
ipptool -tv ipps://EPSON%20ET-1810%20Series._ipps._tcp.local/ get-printer-attributes.test > output.txt
```
the command sends a query to the printer to find out what are the features/settings available on the printer - it can give us idea why ```everywhere``` model doesn't work there.

===========================================================

2. The information that your printer works with dnssd when you add it via Web interface and ipps uri you've been using - IMO it is not an uri which a human can set up by himself - you've probably copied it from somewhere - probably from CUPS web ui or ```lpinfo -v```. And CUPS IPP backend doesn't discover devices automatically like that, so my guess is it is an uri from ```driverless``` backend.

Would you mind installing your queue by the following command and tell us whether the queue works:

```
$ lpadmin -p <name> -v ipps://EPSON%20ET-1810%20Series._ipps._tcp.local/ -m driverless:ipps://EPSON%20ET-1810%20Series._ipps._tcp.local/ -E
```

?

=============================================================

@michaelrsweet if it is not a bug in PPD generator in CUPS, it can be a device which supports driverless standard we still don't support in CUPS - f.e. https://github.com/apple/cups/issues/6022 - it seems like some devices support only PCLm, which CUPS doesn't support yet.

**Comment by Zeioth** [comment] 2022-02-25 03:53
Hello apologies for the delay:

1. The output from ipptool don't show everywhere, but it shows airprint.
[output.txt](https://github.com/OpenPrinting/cups/files/8138291/output.txt)

2. The second command, prints correctly without needing drivers!! Neat!

**Comment by zdohnal** [comment] 2022-02-25 09:25
From the get-printer-attributes.test output:

```
document-format-supported (1setOf mimeMediaType) = application/octet-stream,image/pwg-raster,application/vnd.epson.escpr
```

The device supports image/pwg-raster format, so ```-m everywhere``` should work - so it is a bug in our PPD generator.

@Zeioth I would like to ask to attach several files (if they don't have .txt suffix, please copy them somewhere, add the suffix and attach them here):

1. get the printer attributes in attributes format which can be passed to printer application - this will help to simulate your printer in my local environment - the resulting file is called printer.attr

```
$ ipptool --ippserver printer.attr ipps://EPSON%20ET-1810%20Series._ipps._tcp.local/ get-printer-attributes.test
```

2. get logs when you print to 'everywhere' queue and when you print to 'driverless' queue - to see differences between successful and bad printing.
- enable cups logs via ```cupsctl --debug-logging```, 
- locate the logs (Fedora, RHEL 8+ and CentOS/CentOS Stream 8+ have logs in journal - accessible with journalctl -u cups, others in /var/log/cups/error_log),
- install the broken queue - ```lpadmin -p epson-et1810 -E -v dnssd://EPSON%20ET-1810%20Series._ipp._tcp.local -m everywhere```
- print to working queue and then to broken queue
- attach error_log here as .txt, or redirect cups related logs from journal ```journalctl -u cups > log.txt```

3. attach generated PPDs for both queues, if there are any (cups-2.4.0 and newer doesn't generate a file for '-m everywhere', but driverless should still generate a file in /etc/cups/ppd) - again I can check for differences between those two.


Thank you in advance!

**Comment by michaelrsweet** [comment] 2022-02-25 14:14
@Zeioth In addition to what @zdohnal requested, please also attach the PPD file in /etc/cups/ppd for the printer so that we can see what is in there. This printer supports Wi-Fi Direct Print Services but not AirPrint or Mopria for some reason (maybe it wasn't able to do the media sensing that AirPrint requires? no media-ready or media-col-ready in there) but has everything needed for IPP Everywhere.

**Comment by Zeioth** [comment] 2022-02-25 22:31
Ok this should be all.
[compresed_files.zip](https://github.com/OpenPrinting/cups/files/8145200/compresed_files.zip)

I only want to point out 2 things:
* In the logs, I first ran a successful print, and after, the borked one.
* There is no borked PPD because /etc/cups/ppd don't even create one if I set "-m everyone" in lpadmin. I only attached the working one generated from:

    lpadmin -p <name> -v ipps://EPSON%20ET-1810%20Series._ipps._tcp.local/ -m driverless:ipps://EPSON%20ET-1810%20Series._ipps._tcp.local/ -E

Btw this command is what I understand by 'working' on this tests.

**Comment by Zeioth** [comment] 2022-02-25 22:32
Feel free to ask me anything, I'll be around.

**Comment by michaelrsweet** [comment] 2022-02-28 16:12
@Zeioth The "-m everywhere" should have produced a PPD file, otherwise the command should have produced an error.

What version of CUPS are you using?

**Comment by zdohnal** [comment] 2022-03-01 12:58
@michaelrsweet from the driverless PPD Zeioth attached I see there is CUPS 2.4.x in use, so IIUC we don't generate PPD there...

```
*cupsVersion: 2.4
```

**Comment by michaelrsweet** [comment] 2022-03-01 13:37
@zdohnal Even temporary queues have PPD files, they just disappear when the temp queues go away. It won't be until CUPS 3.0 that we do away with PPDs...

**Comment by zdohnal** [comment] 2022-03-02 10:00
@Zeioth IMHO the issue is about your printer doesn't work with IPP Everywhere, which seems to be related to image/pwg-raster printers such as yours (because my printer supports application/pdf document format and works fine).

I admit I was confused several times at this issue because of typos in your comment, so I needed to confirm that you actually passed the correct options into the command, and because of improper option usage for the job you were trying to do - but hopefully now we are on the same page after the video.

Ad the issue, if you don't take it as 'messing with conversation', even if I'm a member of CUPS community which investigate and fix issues like yours - I've recreated your printer as my virtual printer via ```ippeveprinter``` application - the printer application advertises the printer on localhost:8000 and once I've installed the permanent IPP Everywhere queue like:

```
$ lpadmin -p test -v ipp://localhost:8000/ipp/print -m everywhere -E
```

and the PPD was created. So I would expect lpadmin couldn't communicate with the printer when you created the queue, so I would try the uri without mdns hostname and if printing works for it, check the logs when you create a queue with mdns hostname - it could be in mDNS resolution in CUPS.

**Comment by zdohnal** [comment] 2022-03-02 11:18
So it would be great if you provided CUPS logs when you install the queue - it could show us some errors if there are any.

Note:
lpadmin adds your printer. Otherwise it wouldn't be in ```lpstat -a```. The problem is it adds the printer as a raw queue, because no PPD was generated. In #343 it helped to have device uri with IP instead of mDNS hostname - your issue looks quite similar.

**Comment by zdohnal** [comment] 2022-03-02 11:41
Ok, I was able to reproduce, the relevant log is:

```
Mar 02 12:32:17 fedora cupsd[4507]: FindDeviceById failed: org.freedesktop.ColorManager.NotFound:device id 'cups-test1' does not exist
Mar 02 12:32:17 fedora cupsd[4507]: test1: Unable to connect to HP LaserJet M1536dnf MFP (42307C)._ipp._tcp.local:631: Temporary failure in name resolution
Mar 02 12:32:17 fedora cupsd[4507]: test1: Generating PPD file from "ipp://HP%20LaserJet%20M1536dnf%20MFP%20(42307C)._ipp._tcp.local/"...
```

Seems we substitute '%20' chars when it is not needed.

**Comment by zdohnal** [comment] 2022-03-02 11:47
@Zeioth Can you verify that you see the similar logs when you create a queue with device uri with mDNS hostname and 'everywhere' model?

Temporary queues aren't affected - they print fine. You hit the issue if you try to create a permanent queue with IPP Everywhere model and mDNS hostname from dnssd or driverless backends. The workaround is to use temp queue or IP/hostname based URI like ```ipp://<IP/hostname>:631/ipp/print```.

**Closed** 2022-03-02 12:46 UTC
Labels: bug, investigating, priority-medium, waiting on reporter

**Comment by zdohnal** [comment] 2022-03-02 12:49
@Zeioth  Can you check if the referenced commit helps you when you install the permanent IPP Everywhere queue with mDNS hostname-based URIs?

I tested the fix in Fedora with temporary queue and permanent queues with IPP Everywhere model and two different uris - one with IP, other with mDNS hostname - all three worked.

**Comment by Zeioth** [comment] 2022-03-03 08:50
Hey good morning! I'm gonna install cups-git from aur and test again.

**Comment by VorpalBlade** [comment] 2022-03-03 12:35
@zdohnal I did not check that before, I assumed that the web UI would be based on the current state of the daemon, not the config file.

I did check now however, and no, I was not able to print immediately after, it took about half a minute to update in this case and allow printing (printer added via lpadmin, test print via lp). This seems problematic and potentially confusing to users.

In addition when adding a printer via the web UI and selecting the discovered IPPS-via-mdns printer: The last step of the "wizard" is to set default printer options. As the printer is still a raw printer at this stage, the only options available are banner pages and policy. This is also a confusing user experience, having to wait a bit and then go back into the printer settings to set page size etc.

**Comment by michaelrsweet** [comment] 2022-03-03 12:43
@zdohnal In this case it isn't the DirtyCleanInterval per-se, but the processing that cupsd needs to do in a background thread to generate the PPD.

@VorpalBlade Unfortunately, the current implementation of cupsd is essentially single-threaded. The whole "resolve and generate the PPD in the background" trick can't be done in the (main) IPP request processing thread, so there is no way with the current implementation to delay a response to the CUPS-Add-Modify-Printer request. But we might be able to do something in admin.cgi to special-case the IPP Everywhere driver and wait until a PPD is found. If you can file a separate bug on that specifically I'll see what can be done...

**Comment by VorpalBlade** [comment] 2022-03-03 12:44
@michaelrsweet Sure, I can do that later today when I have more time. What about the case of the user adding the printer through the Gnome printer settings though? Or the KDE ones (I assume it has it's own separate one).

**Comment by michaelrsweet** [comment] 2022-03-03 12:58
@VorpalBlade Note it in the bug and we'll figure something out. It is a "short term" problem as future CUPS won't have this issue (no more PPD files... :), but I'd like to do something about it because it is definitely confusing.

**Comment by Zeioth** [comment] 2022-03-04 06:51
Thank you for pointing that out @zdohnal you right, the cups AUR repos are outdated. I hope I can find time this week to fix that aur repo and make it point here.

I'm not gonna try compiling directly from git because I'd rather to avoid garbage in my system. I'll re-test the issue once it reaches arch offiical repos.

**Comment by VorpalBlade** [comment] 2022-03-04 08:18
> Thank you for pointing that out @zdohnal you right, the cups AUR repos are outdated. I hope I can find time this week to fix that aur repo and make it point here.
> 
> I'm not gonna try compiling directly from git because I'd rather to avoid garbage in my system. I'll re-test the issue once it reaches arch offiical repos.

I just took the official repo CUPS one, modified the PKGBUILD to include the commit as a patch and rebuilt it. I can upload my PKGBUILD & associated files as a tarball somewhere if you want.

**Comment by Zeioth** [comment] 2022-03-04 14:29
@VorpalBlade Yes please, I have enough time to test if you could.

**Comment by VorpalBlade** [comment] 2022-03-04 16:14
> @VorpalBlade Yes please, I have enough time to test if you could.

[cups.tar.gz](https://github.com/OpenPrinting/cups/files/8187212/cups.tar.gz)

**Comment by Zeioth** [comment] 2022-03-05 09:06
Ok I tried the next commands generating the arch package from your PGKbuild and the PPD still doesn't get generated by any of the commands I tried:

    lpadmin -p epson-et1810 -v ipps://EPSON%20ET-1810%20Series._ipps._tcp.local/ -m everywhere -E
    lpadmin -p epson-et1810 -v ipp://192.168.1.101:631/ipp/print -m everywhere -E

Also It's very easy to notice when the command is not creating the PPD in /etc/cups... because the command runs instantly, while when the PPD is created correctly there is an small delay before the command finishes (like with the one it works for me)

    lpadmin -p epson-et1810 -v ipps://EPSON%20ET-1810%20Series._ipps._tcp.local/ -m driverless:ipps://EPSON%20ET-1810%20Series._ipps._tcp.local/ -E

**Comment by zdohnal** [comment] 2022-03-07 08:55
@Zeioth If you still check the existence of PPD by your constructed command, which checks the PPD right after lpadmin exits, you probably hits the delay in PPD generation as described in #347 . The PPD gets generated after some delay depending on your network setup (f.e. I get my IPP Everywhere generated in matter of seconds - 2-3s, so IMO it is influenced by the network setup?). In the end, the PPD should get generated in some time - please check /etc/cups/ppd folder after several seconds.

**Comment by Zeioth** [comment] 2022-03-07 09:07
No, it's not created no matter what. (Ryzen 5950 + 1Gb internet connection. /etc/cups/ppd remains empty after 5 minutes).

**Comment by zdohnal** [comment] 2022-03-07 11:16
@Zeioth can you attach a txt file with CUPS debug logs?

**Comment by debiantriage** [comment] 2022-03-07 18:45
> ```
> lpadmin -p epson-et1810 -v ipps://EPSON%20ET-1810%20Series._ipps._tcp.local/ -m driverless:ipps://EPSON%20ET-1810%20Series._ipps._tcp.local/ -E
> ```

@Zeioth What output does that command produce?

**Comment by zdohnal** [comment] 2022-03-08 09:56
@debiantriage Hi Bryan,

have you applied the latest patch from git master regarding the issue?

**Comment by Zeioth** [comment] 2022-03-08 10:18
@debiantriage That's the only command that works for me so far. It creates the PPD correctly under /etc/cups/ppd

**Comment by debiantriage** [comment] 2022-03-08 10:19
@zdohnal Hello Zdenek,

I forgot about about those patches. Reminding me was good.
Patching and building CUPS is not in my skill set, so I will wait on an updated Debian package.

Apologies for the noise and thank you for your work.

**Comment by zdohnal** [comment] 2022-03-08 10:52
@debiantriage np, please let me know if it helps - there is a known connected issue #347 about a possible delay between the time when lpadmin/CUPS Web UI finishes adding the queue, but the background thread generating the PPD hasn't finished yet - which causes CUPS Web UI/lpoptions showing the queue as a raw for some time.

**Comment by debiantriage** [comment] 2022-07-11 13:49
@zdohnal @michaelrsweet @Zeioth 

Debian now has a cups 2.4.2-1 package. The cups changelog has
Issues #340, #343 as fixed:
> - mDNS hostname in device uri is not resolved when installaling a permanent  IPP Everywhere queue 

Repeating **TEST 1**:

`root@test:~# lpstat -l -e`
`ENVY4500 network none ipp://ENVY4500._ipp._tcp.local/`

```
lpadmin -p testq -v ipp://ENVY4500._ipp._tcp.local/ -E -m everywhere
```
This command completes and immediately produces a PPD.

`root@test:~# ls -l /etc/cups/ppd/`
`-rw-r----- 1 root lp 14770 Jul 11 14:41 testq.ppd`

That's an improvement on the previous outcome. The issue seems to me to be fixed.
