### ISSUE TITLE
libcups returns success if scheduler does not send data in time (f.e. cups-driverd times out)

### ISSUE THREAD

**Issue by guillaumesoucy94** [OpenPrinting/cups#893] opened 2024-02-15 01:01 UTC
**Describe the bug**
"There was an error during cups operation: success" when adding a remote printer using LPR. In cups webGUI, I'd entered the same printer address than in the Linux Mint add printer GUI, nothing happens when clicking "Continue". The page just get reloaded.

**To Reproduce**
Steps to reproduce the behavior on CUPS webGUI:
1. Go to 'Add printers'
2. Fill with info
3. Click continue 
4. nothing happens.

Steps to reproduce the behavior on Linux Mint add printers:
1. Go to 'Add printers'
2. Fill with info
3. Click continue 
4. "There was an error during cups operation: success".

**Expected behavior**
On both Linux GUI and CUPS webGUI, the select driver interface supposed to show up.

**Screenshots**
![Screenshot at 2024-02-14 19-50-20](https://github.com/OpenPrinting/cups/assets/22561876/5372fc47-7ede-451c-921a-2e9d2d71436d)

**System Information:**
 - OS and its version: Linux Mint 21.3 x64
 - CUPS version 2.4.1

**Additional context**
I did search and, there was similar issues but not exactly what covering my problem. 
I do have 3 other printers on the system. 
Since few time, I do have the same error when adding other printers as well.

**Comment by zdohnal** [comment] 2024-02-15 06:51
Hi,

please turn on CUPS debugging, reproduce the issue and upload the logs here with .txt suffix.

**Comment by guillaumesoucy94** [comment] 2024-07-03 18:24
Hello, 

Sorry for the delays. 

When reproducing the issue, it only writing lines in access_log , nothing in error_log . 

[access_log.txt](https://github.com/user-attachments/files/16089203/access_log.txt)

It affect also another computer, in the same way.

Guillaume

**Comment by guillaumesoucy94** [comment] 2024-07-05 12:49
Is that issue can be reopened? I still have an issue.

**Comment by zdohnal** [comment] 2024-07-08 12:12
No logs in error_log is strange - have you enabled the CUPS debug logging? Or do you redirect logs into syslog/journal?

I don't plan to reopen until I have at least logs to examine.

**Comment by guillaumesoucy94** [comment] 2024-07-11 18:29
This is what we're looking for:

[error_log.txt](https://github.com/user-attachments/files/16182096/error_log.txt)


Guillaume

**Comment by zdohnal** [comment] 2024-07-12 05:52
I see from the logs:

```
D [11/Jul/2024:14:23:55 -0400] [CGI] Started ippfind (PID 656011)
I [11/Jul/2024:14:23:56 -0400] Expiring subscriptions...
D [11/Jul/2024:14:24:54 -0400] [Client 6] Closing on unexpected HTTP read state HTTP_STATE_POST_SEND.
D [11/Jul/2024:14:24:54 -0400] [Client 6] Closing connection.
D [11/Jul/2024:14:24:54 -0400] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
I [11/Jul/2024:14:24:54 -0400] Expiring subscriptions...
D [11/Jul/2024:14:24:54 -0400] Report: clients=2
D [11/Jul/2024:14:24:54 -0400] Report: jobs=0
D [11/Jul/2024:14:24:54 -0400] Report: jobs-active=0
D [11/Jul/2024:14:24:54 -0400] Report: printers=0
D [11/Jul/2024:14:24:54 -0400] Report: stringpool-string-count=397
D [11/Jul/2024:14:24:54 -0400] Report: stringpool-alloc-bytes=5624
D [11/Jul/2024:14:24:54 -0400] Report: stringpool-total-bytes=6784
D [11/Jul/2024:14:24:54 -0400] PID 655985 (/usr/lib/cups/daemon/cups-driverd) was terminated normally with signal 9.
```

I see starting ippfind, but no end of it - probably we could see more when debug2 was enabled, but I kind of recall this was an issue in the past - ippfind from driverless backend from cups-filters project took too long, causing listing drivers to timeout.
For sure we should not end with "success", but otherwise it is not CUPS issue.

Can you try some latest versions of cups-filters? 2.0.0 or such - based on CUPS version I guess cups-filters there will be pretty old too.

**Comment by zdohnal** [comment] 2024-07-12 07:40
To emphasize - the fix here will be only change of error message, otherwise the issue lies in the other project -> cups-filters, but I would guess the issue is fixed in newer cups-filters releases.
Basically, cups-filters needs to tell ippfind to end within reasonable time.

**Comment by guillaumesoucy94** [comment] 2024-07-18 13:54
So, I just need to update CUPS on those two machines? 

Simple as that?

**Comment by zdohnal** [comment] 2024-07-19 04:39
Not cups, but cups-filters - two different projects on Github and two different packages. And first - I don't know for sure, but I'm running on latest projects versions in Fedora and I don't see the issue, the second - I speak from the project perspective. Whether the latest upstream versions are in your OS, that's the question for your distro maintainers.

**Closed** 2024-07-24 07:03 UTC
Labels: waiting for reporter
