### ISSUE TITLE
May 'cancel -a -x' also delete temporary files in /var/spool/cups/tmp ?

### ISSUE THREAD

**Issue by jsmeix** [OpenPrinting/cups#512] opened 2022-10-27 07:09 UTC
Currently I use CUPS 2.4.2 where
`cancel -a -x` deletes all files in /var/spool/cups/
(i.e. all print job data and control files)
except temporary files in /var/spool/cups/tmp.

Reasoning:
I wonder if `cancel -a -x` is allowed to
also delete all files in /var/spool/cups/tmp
or if those temporary files belong to other programs
so that CUPS must not delete them?
But if not CUPS what else should or could delete them?
I know that not all programs that create files in
/var/spool/cups/tmp clean them up properly in any case
so over time leftover files pile up in /var/spool/cups/tmp
and then I think it would be nice if `cancel -a -x` could
"by the way" also clean up /var/spool/cups/tmp.

**Comment by zdohnal** [comment] 2022-10-27 09:29
Hi @jsmeix ,

which setup (PPD + connection) leaves additional files in ```/var/spool/cups/tmp```? Currently I see there only lockfile for dbus notifier, so we can't clean up all files from the directory. Since ```-x``` option works for job id and printer names, it would have to work for those as well - and I'm not sure whether we are able to decide which temp files belong to which job/printer, because each binary using the temp files can use a different name syntax for its filenames...

IMHO the only sure way is to find out which binary doesn't clean up after itself and fix it there if possible - if it is not feasible, understand its filename syntax and create a cron job which will delete such files. WDYT, @michaelrsweet ?

**Comment by jsmeix** [comment] 2022-10-27 09:56
I meant it for the `cancel -a -x` "clean up all" case
i.e. when nothing else is specified.

**Comment by jsmeix** [comment] 2022-10-27 10:03
My printing tests of today in
https://github.com/OpenPrinting/cups/issues/510
resulted a
```
# file /var/spool/cups/tmp/foomatic-hhBitj
/var/spool/cups/tmp/foomatic-hhBitj: PDF document, version 1.3
```
that has at its beginning
```
%PDF-1.3
%277367242376
% This file was generated by pdftopdf
%%PDFTOPDFNumCopies : 1
%%PDFTOPDFCollate : false
1 0 obj
<< /Pages 3 0 R /Type /Catalog >>
endobj
2 0 obj
<< /Author (johannes) /CreationDate (D:20221027082136+02'02') /Creator (texttopdf/1.25.0) /Title (os-release) >>
```
Its content is a PDF of /etc/os-release, cf.
https://github.com/OpenPrinting/cups/issues/510#issuecomment-1293039371

**Comment by zdohnal** [comment] 2022-10-27 10:30
@jsmeix 

> I meant it for the `cancel -a -x` "clean up all" case i.e. when nothing else is specified.

The problem is that IMHO we can't clean up all files, only jobs related files with ```cancel -a -x``` - and it seems not just job-related files go to the directory.


Ad #510 I've tried reproducing the issue with CUPS 2.4.2 and cups-filters 1.28.16 and I don't have such file there.

The print queue was installed like this:

```
$ lpadmin -p ricoh2 -v file:/tmp/ps -P Ricoh-SP_377SFNwX-pxlmono-Ricoh.ppd -E
```

where the PPD is from the OpenPrinting website, and tried to print ```/etc/os-release``` as you did, but no temp file from foomatic for me:

```
[root@fedora ~]# ls -lah /var/spool/cups/tmp/
total 8.0K
drwxrwx--T. 2 root lp 4.0K Oct 27 12:28 .
drwx--x---. 3 root lp 4.0K Oct 27 12:28 ..
-rw-------. 1 lp   lp    0 Oct 27 07:06 cups-dbus-notifier-lockfile
```

Can it be possible you don't have the latest 1.x cups-filters release?

**Comment by jsmeix** [comment] 2022-10-27 11:30
On my homeoffice laptop I run various non-standard versions where
currently I have cups-filters-1.25.0 (Leap 15 has cups-filters-1.20.3)
but the newer one form openSUSE OBS Printing project needs a newer libqpdf
and currently I don't have time for such stunts...

Just let us leave this issue RIP.

**Comment by zdohnal** [comment] 2022-10-27 11:40
Ok, I'll close it for now.

**Closed by zdohnal** 2022-10-27 11:40 UTC
Labels: wontfix
