### ISSUE TITLE
kyocera 255 - 3.4 ci cannot print

### ISSUE THREAD

**Issue by listocheklss** [OpenPrinting/cups#930] opened 2024-04-06 09:38 UTC
**Before you write the report**
Read the [REPORTING_ISSUES.md](https://github.com/OpenPrinting/cups/blob/master/REPORTING_ISSUES.md) file in the main repository and prepare data mentioned there which looks relevant to you issue.

**Describe the bug**
kyocera 255 - 3,4 ci не могут выполнить печать в результате чего приходится перезапускать принтер вручную
kyocera 255 - 3.4 ci cannot print, as a result of which you have to restart the printer manually

**To Reproduce**
[print.odg](https://github.com/OpenPrinting/cups/files/14893112/print.odg)
2. Click on '....'  print
4. Scroll down to '....' 
5. See error

**Expected behavior**

**Screenshots**

**System Information:**
 - OS and its version: [e.g. Ubuntu 22.04, Fedora 37, MacOS 13.0 Ventura...]
 - Application [e.g. chrome, safari, evince...]
 - CUPS version [e.g. 2.4.2]
Операционная система: ALT 10.2
Версия KDE Plasma: 5.27.8
Версия KDE Frameworks: 5.110.0
Версия Qt: 5.15.11
Версия ядра: 6.1.57-un-def-alt1 (64-бита)
Графическая платформа: X11
Процессоры: 4 × Intel® Core™ i5-7400 CPU @ 3.00GHz
Память: 15,5 ГиБ ОЗУ
Графический процессор: Mesa Intel® HD Graphics 630
OpenPrinting CUPS 2.4.7

**Additional context**
Any additional information which are relevant to the issue.

**Comment by michaelrsweet** [comment] 2024-04-16 14:36
How is the printer connected to the system? (`lpstat -v` will show)

What driver (if any) are you using with the printer?

The description seems to indicate that you can't print, but you can restart the printer? I'm not sure I understand what the issue is?

**Comment by listocheklss** [comment] 2024-04-16 15:00
1.  1_floor_kor_Color_2553ci: ipp://*.*.*.*/ipp
2.  IPP Everywhere TM
    Kyocera TASKalfa 2553ci (KPDL), driverless, cups-filters 1.28.11 (en)
3. The file comes to print, falls into the task and hangs. When you click cancel, it says that the task is canceled and waits indefinitely for cancellation.
Файл приходит на печать, падает в задание и висит. При нажатии на отмена пишет что задание отменяется и до бесконечности ожидание отмены.

**Comment by michaelrsweet** [comment] 2024-08-14 04:25
We'll need debug logs (run `cupsctl --debug-logging`, then print something) to see what filters are running.

Also, have you tried printing something from the command-line (not just from a GUI)?

**Comment by listocheklss** [comment] 2024-09-04 11:59
[error_log.txt](https://github.com/user-attachments/files/16869822/error_log.txt)
I started a task from my computer that had an error, but it printed out. However, I removed the logs.
We will wait for the next case
Запустил со своего компьютера задание которое с ошибкой, но оно распечаталось. Однако логи снял.

**Comment by listocheklss** [comment] 2024-09-05 08:28
[error_log.txt](https://github.com/user-attachments/files/16886280/error_log.txt)
Here I caught a case, cups 2.3.3op2 fixes the problem in place. There is no problem on my computer anymore. Of course we will update it. But I would like to know in more detail what kind of errors these are that hang up the device.
Вот поймал случай, на месте проблема фиксируется cups 2.3.3op2. На моем компьютере уже проблемы нет. Обновлять конечно будем. Но хочется знать подробнее, что это за ошибки такие которые вешают аппарат.

**Comment by zdohnal** [comment] 2024-09-06 08:59
@listocheklss so which one is the one with error? You write cups 2.3.3op2 fixes the issue, but the last log shows it has CUPS 2.3.3op2 and shows an error from the printer:

```
D [05/Sep/2024:09:21:31 +0300] [Job 3496] ---- end-of-attributes-tag ----
D [05/Sep/2024:09:21:31 +0300] [Job 3496] System error. Turn the main power switch off and on.
D [05/Sep/2024:09:21:31 +0300] [Job 3496] update_reasons(attr=2(paused,...), s=\"(null)\")
```

so in this case the file was printed? Even through the error? The log shows job was completed.

The log with CUPS 2.4.7 (one before the last) shows the successful job - it would be great if you got the error log when the error happens.

**Comment by listocheklss** [comment] 2024-09-06 09:08
apparently the translation worked differently. 2.3.3.or2 an error is fixed on this version.
My computer is running 2.4.7 and the error does not reproduce on this version.
видимо перевод сработал иначе. 2.3.3.ор2  на этой версии фиксируется ошибка.
На моём же компьютере стоит 2.4.7 и на этой версии ошибка не воспроизводится

**Comment by zdohnal** [comment] 2024-09-06 14:26
@listocheklss so what CUPS version is affected? I understand from your comment that both version you mention work :) .

**Comment by listocheklss** [comment] 2024-09-06 18:39
error 2.3.3 op2

**Comment by michaelrsweet** [comment] 2024-09-20 16:51
OK, so as I understand it, the current 2.4.x releases work but the old 2.3.3op2 release doesn't, so we can close this as fixed.

**Closed by michaelrsweet** 2024-09-20 16:51 UTC
Labels: waiting for reporter

**Comment by listocheklss** [comment] 2024-11-05 11:08
There are new clarifications. And the problem repeats itself but in the new version 2.4.11.
These cases occur with pdf documents and are divided into 2 types 
1) I could not print any amount and 0 pages are displayed in the printer
2) I was able to print several sheets or one and stopped too.
Explanation: The problem manifests itself both in the browser when printing and in okular.
When testing the Print as Image function, the document is printed, but you must not forget to restart everything after stopping the printer.
Есть новые уточнения. И проблема повторяется но новой версии 2.4.11.
Данные случаи происходят с pdf документами и делятся на 2 типа 
1) не смог ни сколько ни распечатать и в принтере отображается 0 стр
2) Смог распечатать несколько листов или один и тоже остановился.
Пояснение: Проблема проявляется и в браузере при печати и в okular.
При тестировании функции Печатать как изображение - документ распечатывается, однако надо не забыть все перезапустить после остановки принтера.
